### ISSUE TITLE
CherryPy dies if a config file value is a dictionary

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1069]
Originally reported by: **guest (Bitbucket: [guest](http://bitbucket.org/guest), GitHub: [guest](http://github.com/guest))**

---

CherryPy allows — nay, requires — that config file values be Python expressions. But if I try to provide a small dictionary that my application needs:

```
[/]
selections = {'noller': 'bacon'}
```

then instead of parsing the dictionary, CherryPy returns:

```

Traceback (most recent call last):
  File "/home/brandon/rover/cory/venv/bin/cherryd", line 108, in <module>
    options.pidfile, options.imports, options.cgi)
  File "/home/brandon/rover/cory/venv/bin/cherryd", line 19, in start
    cherrypy.config.update(c)
  File "/home/brandon/rover/cory/venv/lib/python2.7/site-packages/cherrypy/_cpconfig.py", line 156, in update
    reprconf.Config.update(self, config)
  File "/home/brandon/rover/cory/venv/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 143, in update
    config = Parser().dict_from_file(config)
  File "/home/brandon/rover/cory/venv/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 214, in dict_from_file
    return self.as_dict()
  File "/home/brandon/rover/cory/venv/lib/python2.7/site-packages/cherrypy/lib/reprconf.py", line 205, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ('Config error in section: \'global\', option: \'selections\', value: "{\'noller\': \'bacon\'}". Config values must be valid Python.', 'AssertionError', ())
```

It seems that the "assert" statement at transformer.py:1214 in the Python 2.7 standard library thinks that a dictionary node should start with a "dictorsetmaker" but instead is seeing what it thinks is a "classdef" node. Is this an error in the deprecated "compiler" Standard Library package (I ran into one of those recently), or an error in how CherryPy is calling it?

And, while all this is on the table: why does CherryPy bother with the parser module and then trying to evaluate the (now deprecated) output, instead of just running "eval()" on configuration file entries?

Thanks for any help in getting this working!

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1069

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — the "config file with a dict value crashes" report no longer reproduces on current main.

Evidence:
- `cherrypy/lib/reprconf.py` parses values via `ast.parse` / `_Builder.astnode` (see `reprconf.unrepr` and `_Builder` around L224-242). The deprecated stdlib `compiler` / `transformer.py` module referenced in the report's traceback is no longer on the codepath.
- `pyproject.toml` declares `requires-python = '>= 3.9'`, so Python 2.7 (where the `transformer` traceback came from) is no longer supported.
- I re-ran the report's repro on current main: `[/]\nselections = {"noller": "bacon"}` parses cleanly to `{'/': {'selections': {'noller': 'bacon'}}}` without raising.

If I'm wrong about dict literals in config now parsing on current main, point me at the doc/version and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*
