### ISSUE TITLE
[Python3.2] [CherryPy==3.2.2] TypeError in cherrypy/lib/httputil.py on line 252

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1167]
Originally reported by: **Sviatoslav Sydorenko (Bitbucket: [webknjaz](http://bitbucket.org/webknjaz), GitHub: [webknjaz](http://github.com/webknjaz))**

---

Versions:

```
#!bash

$ python3 -V
Python 3.2.3

$ pip-3.2 freeze
CherryPy==3.2.2
```

While trying to use cherrypy TypeError exception raises.

i.e.

```
#!bash

$ nosetests-3.2 -s ./
E
======================================================================
ERROR: Failure: TypeError ('tuple' object is not callable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/site-packages/nose/failure.py", line 37, in runTest
    raise self.exc_class(self.exc_val).with_traceback(self.tb)
  File "/usr/local/lib/python3.2/site-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python3.2/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python3.2/site-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/wk/cherrypy/cherrypy/__init__.py", line 74, in <module>
    from cherrypy import _cprequest
  File "/home/wk/cherrypy/cherrypy/_cprequest.py", line 172, in <module>
    class Request(object):
  File "/home/wk/cherrypy/cherrypy/_cprequest.py", line 396, in Request
    error_response = cherrypy.HTTPError(500).set_response
  File "/home/wk/cherrypy/cherrypy/_cperror.py", line 342, in __init__
    self.code, self.reason, defaultmsg = _httputil.valid_status(status)
  File "/home/wk/cherrypy/cherrypy/lib/httputil.py", line 252, in valid_status
    status = str(status)
TypeError: 'tuple' object is not callable

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1167

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this `TypeError` in `valid_status` on Python 3.2 looks long-gone.

Evidence:
- `cherrypy/lib/httputil.py` rewrites `valid_status` to use `isinstance(status, str)` + `status.partition(' ')` + `int(code)`; it no longer calls `str(status)` on an `http.client` constant tuple, which is what blew up in the report.
- `pyproject.toml` requires `>= 3.9`, so Python 3.2 (the version named in the title and traceback) is far outside the supported matrix anyway — the original code path is gone.

If I'm wrong about `valid_status` no longer reproducing this `TypeError` on a supported runtime, point me at the doc/version and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references above were verified manually.*
