### ISSUE TITLE
Internal server errors: /?1,1a and malformed request line

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1172]
Originally reported by: **space one (Bitbucket: [spaceone](http://bitbucket.org/spaceone), GitHub: [spaceone](http://github.com/spaceone))**

---

2 more errors:

/?1,1a or /?1,1&foo=bar

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 640, in respond
    self.process_query_string()
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 682, in process_query_string
    self.query_string, encoding=self.query_string_encoding)
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/httputil.py", line 347, in parse_query_string
    pm = {'x': int(pm[0]), 'y': int(pm[1])}
ValueError: invalid literal for int() with base 10: '1a'

the regex pattern is wrong, it has to be: r"^[0-9]+,[0-9]+$"

Another Traceback:
echo -en 'GET abcd HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' | nc 127.0.0.1 8090
ends up in internal server error, but this is a client error because the request line is malformed

ENGINE TypeError("argument of type 'NoneType' is not iterable",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1292, in communicate
    req.parse_request()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 580, in parse_request
    success = self.read_request_line()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 644, in read_request_line
    if NUMBER_SIGN in path:
TypeError: argument of type 'NoneType' is not iterable

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1172

**Comment by webknjaz** [comment]
This is handled by the current version of Cheroot
