### ISSUE TITLE
cherrypy-3.2.4 test failures; py2.5,2.6,3.1,3.3, pypy

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1260]
Originally reported by: **idella5 (Bitbucket: [idella5](http://bitbucket.org/idella5), GitHub: [idella5](http://github.com/idella5))**

---

py2.5 2.6, 3.1,  yield

ERROR: login_screen must return bytes even if unicode parameters are passed.

3.1 also

``` python
ERROR: test_HTTP11_pipelining (cherrypy.test.test_conn.PipelineTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/test_conn.py", line 428, in test_HTTP11_pipelining
    response.begin()
  File "/usr/lib64/python3.1/http/client.py", line 352, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.1/http/client.py", line 314, in _read_status
    raise BadStatusLine(line)
nose.proxy.BadStatusLine: 
```

3.3

test_HTTP11_pipelining (cherrypy.test.test_conn.PipelineTests) ... ERROR
then

``` python
testCookies (cherrypy.test.test_core.CoreRequestHandlingTest) ... 
```

and there she hangs.

pypy2.0;

``` python
ERROR: testNormalReturn (cherrypy.test.test_logging.AccessLogTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/test_logging.py", line 82, in testNormalReturn
    self.assertLog(-1, intro)
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/logtest.py", line 170, in assertLog
    if lines not in data[sliceargs]:
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
cherrypy.access.80970208: INFO: 127.0.0.1 - - [25/Jul/2013:23:41:45] "GET /as_string HTTP/1.1" 200 7 "http://www.cherrypy.org/" "Mozilla/5.0"
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: testNormalYield (cherrypy.test.test_logging.AccessLogTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/test_logging.py", line 101, in testNormalYield
    self.assertLog(-1, intro)
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/logtest.py", line 170, in assertLog
    if lines not in data[sliceargs]:
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
cherrypy.access.80970208: INFO: 127.0.0.1 - - [25/Jul/2013:23:41:45] "GET /as_yield HTTP/1.1" 200 7 "" ""
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: testTracebacks (cherrypy.test.test_logging.ErrorLogTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/test_logging.py", line 153, in testTracebacks
    self.assertLog(0, 'HTTP Traceback (most recent call last):')
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/logtest.py", line 170, in assertLog
    if lines not in data[sliceargs]:
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus STOPPING
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 54583)) shut down
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Stopped thread '_TimeoutMonitor'.
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus STOPPED
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus EXITING
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus EXITED
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Listening for SIGHUP.
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Listening for SIGTERM.
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Listening for SIGUSR1.
cherrypy.test.helper: INFO: Python version used to run this test script: 2.7.3
cherrypy.test.helper: INFO: CherryPy version: 3.2.4
cherrypy.test.helper: INFO: HTTP server version: HTTP/1.1
cherrypy.test.helper: INFO: PID: 9885
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus STARTING
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Started monitor thread '_TimeoutMonitor'.
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Serving on 127.0.0.1:54583
cherrypy.error: INFO: [25/Jul/2013:23:41:46] ENGINE Bus STARTED
cherrypy.error.67110296: ERROR: [25/Jul/2013:23:41:46] HTTP Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/gen2/TmpDir/portage/dev-python/cherrypy-3.2.4/work/CherryPy-3.2.4/cherrypy/test/test_logging.py", line 51, in error
    raise ValueError()
ValueError

cherrypy.access.67110296: INFO: 127.0.0.1 - - [25/Jul/2013:23:41:46] "GET /error HTTP/1.1" 500 1518 "" ""
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 235 tests in 117.138s

FAILED (SKIP=2, errors=4)
```

I suspect these tests need rewriting for the corresponding python versions but the -3.2.4  doesn't qualify for adding to portage @ gentoo until these are fixed.  Until then they are either tests not up to testing for the corresponding versions OR genuine bugs

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1260

**Comment by webknjaz** [comment]
Fixed via cherrypy/cheroot@fa5d8e9 ([CI](https://travis-ci.org/cherrypy/cheroot/jobs/247741229#L216))
