### ISSUE TITLE
pip uninstall cherrypy error

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1289]
Originally reported by: **combix (Bitbucket: [combix](http://bitbucket.org/combix), GitHub: [combix](http://github.com/combix))**

---

Installing cherrypy with pip is great! 

```
#!batch

PS C:\> pip install cherrypy
Downloading/unpacking cherrypy
  Downloading CherryPy-3.2.4.tar.gz (424Kb): 424Kb downloaded
  Running setup.py egg_info for package cherrypy
Installing collected packages: cherrypy
  Running setup.py install for cherrypy
Successfully installed cherrypy
```

(aside: I can't import cherrypy due to 'ImportError: cannot import name CREATE_NEW_PROCESS_GROUP')

But the issue I'm reporting is that then I can't uninstall cherrypy

PS C:> pip uninstall cherrypy

```
#!batch

Uninstalling CherryPy:
  c:\python26\lib\site-packages\cherrypy
  c:\python26\lib\site-packages\cherrypy-3.2.4-py2.6.egg-info
  c:\python26\scripts\cherryd
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "C:\Python26\lib\site-packages\pip\basecommand.py", line 115, in main
    self.run(options, args)
  File "C:\Python26\lib\site-packages\pip\commands\uninstall.py", line 37, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "C:\Python26\lib\site-packages\pip\req.py", line 763, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "C:\Python26\lib\site-packages\pip\req.py", line 452, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\Python26\lib\site-packages\pip\req.py", line 1464, in remove
    renames(path, new_path)
  File "C:\Python26\lib\site-packages\pip\util.py", line 312, in renames
    shutil.move(old, new)
  File "C:\Python26\lib\shutil.py", line 260, in move
    raise Error, "Cannot move a directory '%s' into itself '%s'." % (src, dst)
Error: Cannot move a directory 'c:\python26\lib\site-packages\cherrypy' into itself 'c:\python26\lib\site-packages\c
ypy'.
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1289

**Comment by webknjaz** [comment]
Looks like @combix either solved the issue or upgraded pip. Appveyor tests don't have this issue.
