### ISSUE TITLE
error_page.404 utf-8 handling error

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1303]
Originally reported by: **Anonymous**

---

Hi, i have russian chars encoded with utf-8 in 404.html

When referring to a nonexistent page get an "500 Internal Server Error"

```
#!python

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Work\Internet\library\python\lib\site-packages\cherrypy\_cprequest.py", line 664, in respond
    inst.set_response()
  File "C:\Work\Internet\library\python\lib\site-packages\cherrypy\_cperror.py", line 376, in set_response
    message=self._message).encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 149: ordinal not in range(128)
Powered by CherryPy 3.2.5
```

Config:

```
#!python

cherrypy.config.update({
        'global': {
             ...
            'error_page.404': r'%s/public/internet/errors/404.html' % WORKING_DIRECTORY
        }
    })
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1303

**Comment by webknjaz** [comment]
It's out-of-date now.

**Comment by pou-chi** [comment]
Error is still here. 
Related issue from Sviatoslav  about utf8 chars at filename, but not content of error_page static file.
The workaround is remove  

> encode('utf-8')

 from 

> return result.encode('utf-8')

**Comment by webknjaz** [comment]
@pou-chi Could you please send us Pull Request with fix and tests?
