### ISSUE TITLE
test_2_File_Concurrency fails intermittently

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1306]
Originally reported by: **Nathan Kinder (Bitbucket: [nkinder](http://bitbucket.org/nkinder), GitHub: [nkinder](http://github.com/nkinder))**

---

I've noticed intermittent failures of the test_2_File_Concurrency test in test_session.py.  I'm using a recent checkout from the default branch (CherryPy 3.2.5 plus whatever has been committed since) with Python 2.7.5.

The failures can be seen by simply running the test_session.py tests in a loop as follows:

```
  for i in `seq 1 100`; do nosetests -s ./test_session.py; done
```

I'm seeing failures about 5% of the time.  Here is an example of the failure output:

```
S..........
----------------------------------------------------------------------
Ran 11 tests in 10.387s

OK (SKIP=1)
S...F......
======================================================================
FAIL: test_2_File_Concurrency (cherrypy.test.test_session.SessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nathank/Source/cherrypy/cherrypy/cherrypy/test/test_session.py", line 218, in test_2_File_Concurrency
    self._test_Concurrency()
  File "/home/nathank/Source/cherrypy/cherrypy/cherrypy/test/test_session.py", line 268, in _test_Concurrency
    self.assertEqual(hitcount, expected)
AssertionError: 150 != 151
-------------------- >> begin captured logging << --------------------
cherrypy.error: INFO: [19/Mar/2014:14:41:18] ENGINE Stopped thread 'Session cleanup'.
cherrypy.access.49232208: INFO: 127.0.0.1 - - [19/Mar/2014:14:41:18] "GET /setsessiontype/file HTTP/1.1" 200 - "" ""
cherrypy.error: INFO: [19/Mar/2014:14:41:18] ENGINE Started monitor thread 'Session cleanup'.
cherrypy.access.49232208: INFO: 127.0.0.1 - - [19/Mar/2014:14:41:18] "GET / HTTP/1.1" 200 1 "" ""
cherrypy.access.49232208: INFO: 127.0.0.1 - - [19/Mar/2014:14:41:18] "GET / HTTP/1.1" 200 1 "" ""
...
cherrypy.access.49232208: INFO: 127.0.0.1 - - [19/Mar/2014:14:41:20] "GET / HTTP/1.1" 200 3 "" ""
cherrypy.access.49232208: INFO: 127.0.0.1 - - [19/Mar/2014:14:41:20] "GET / HTTP/1.1" 200 3 "" ""
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 11 tests in 10.406s

FAILED (SKIP=1, failures=1)
S..........
----------------------------------------------------------------------
Ran 11 tests in 10.505s

OK (SKIP=1)
```

This looks very similar to ticket #799, which was resolved long ago.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1306

**Comment by jaraco** [comment]
This is one of the intermittent test failures we're [seeing more frequently in Travis](https://travis-ci.org/cherrypy/cherrypy/jobs/186430884) after switching to pytest.

**Comment by webknjaz** [comment]
@jaraco so this looks like concurrency issues with file locking to me. I'm not sure how to debug that, though.

**Comment by dotlambda** [comment]
On NixOS, it seems like skipping this test makes two other tests (SessionTest.test_3_Redirect and SessionTest.test_4_File_deletion) fail. These failures are reproducible.

**Comment by webknjaz** [comment]
@dotlambda thanks for the report! mind sending us a contribution to fix this?

**Comment by jaraco** [comment]
It does seem this issue has increased dramatically, like from 5% to 95% between 17.x and 18.x. I'm going to bisect and find the cause.

**Comment by jaraco** [comment]
Oh, git bisect implicated 58a6e40b7bdc4adfe03e57f918ab62789cfbe366. Well, that explains the increase in _reported_ failures.

**Comment by webknjaz** [comment]
Yeah... I've tried to debug the root of the issue and wanted it to be reported. So I've dropped that skip. Turned out too complicated and got postponed.

**Comment by jaraco** [comment]
No problem. And I now see the link to that commit above (/me needs to get better at reading GitHub). I'm going to revert that commit so the test isn't blocking other work.

**Comment by jaraco** [comment]
Test once again expects to fail in c3eaf0f1.
