### ISSUE TITLE
Invalid dictionary ordering assumption in test_0_Session

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1328]
Originally reported by: **Barry Warsaw (Bitbucket: [warsaw](http://bitbucket.org/warsaw), GitHub: [warsaw](http://github.com/warsaw))**

---

test_0_Session in test_session.py makes an assumption about dictionary iteration order, which is invalid and breaks in some test runs.  Specifically, the Debian package test fails.

```
#!python

======================================================================
FAIL: test_0_Session (cherrypy.test.test_session.SessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.btPR4P/dsc0-build/cherrypy3-3.5.0/cherrypy/test/test_session.py", line 162, in test_0_Session
    self.assertBody("{'aha': 'foo', 'counter': 3}")
  File "/tmp/adt-run.btPR4P/dsc0-build/cherrypy3-3.5.0/cherrypy/test/webtest.py", line 404, in assertBody
    self._handlewebError(msg)
  File "/tmp/adt-run.btPR4P/dsc0-build/cherrypy3-3.5.0/cherrypy/test/webtest.py", line 310, in _handlewebError
    raise self.failureException(msg)
nose.proxy.AssertionError: expected body:
b"{'aha': 'foo', 'counter': 3}"

actual body:
b"{'counter': 3, 'aha': 'foo'}"
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1328

**Comment by jaraco** [comment]
Fixed in e07b4197889.
