### ISSUE TITLE
Uncaught Socket Exception in 2.3.0

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1351]
Originally reported by: **Anonymous**

---

I'm using CherryPy 2.3.0 for legacy reasons.  Since the wsgi server code has been refactored in version 3 I don't know if this issue still exists or not, but I thought I'd report the issue in 2.3.0 just to be safe.  

I'm getting the following exception:

Exception in thread CP WSGIServer Thread-9:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\cherrypy-2.3.0-py2.7.egg\cherrypy_cpwsgiserver.py", line 253, in run
    request.terminate()
  File "C:\Python27\lib\site-packages\cherrypy-2.3.0-py2.7.egg\cherrypy_cpwsgiserver.py", line 211, in terminate
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 279, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10054] An existing connection was forcibly closed by the remote host

When this happens the worker thread dies.  If all of the worker threads die then cherry py no longer responds to requests.

The issue is that cpwsgiserver.py line 253: request.terminate() is in a finally block, but it can throw an exception.  

I'm running CherryPy on Win7.  I encounter the exception if I have an Ajax call in progress and then do a page reload.  The exception occurs when browsing in both FireFox and IE.

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1351

**Comment by webknjaz** [comment]
Ref: #1403
