### ISSUE TITLE
404 response for non-ascii URL has encoding errors

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1360]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

Create a simple hello world, such as this one:

```
import cherrypy

class Server:
    @cherrypy.expose
    def index(self):
        return "OK!"

    @classmethod
    def run(cls):
        config = {
            'global': {
                'server.socket_host': '::0',
            }
        }
        cherrypy.quickstart(cls(), config=config)


if __name__ == '__main__':
    Server.run()
```

And launch it under Python 3 with CherryPy 3.6 and request `/£` or `/%C2%A3`. The server returns this 404 error:

```
404 Not Found

The path '/Â£' was not found.

Traceback (most recent call last):
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Users\jaraco\p\cherrypy\cherrypy\lib\encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cperror.py", line 411, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/Â£' was not found.")

Powered by CherryPy 3.6.1 
```

The spurious character in the error message betrays an encoding problem.

On Python 2, the 404 becomes a 500 when the decoding fails:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cprequest.py", line 678, in respond
    inst.set_response()
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cperror.py", line 401, in set_response
    message=self._message)
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cperror.py", line 407, in get_error_page
    return get_error_page(*args, **kwargs)
  File "C:\Users\jaraco\p\cherrypy\cherrypy\_cperror.py", line 535, in get_error_page
    return result.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 520: ordinal not in range(128)

Powered by CherryPy 3.6.1 
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1360

**Comment by webknjaz** [comment]
@jaraco is this still reproducible?

**Comment by jaraco** [comment]
I would imagine so, though I haven't tried.

**Comment by webknjaz** [comment]
This is out-of-date and looks fixed to me.
