### ISSUE TITLE
Get Error message ENGINE AttributeError("'module' object has no attribute 'socket_errors_to_ignore'",)

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1376]
Originally reported by: **George Weinberg (Bitbucket: [gweinberg](http://bitbucket.org/gweinberg), GitHub: Unknown)**

---

I sometimes get an error message from cherrypy 
 ENGINE AttributeError("'module' object has no attribute 'socket_errors_to_ignore'",)

I don't know what's causing it to check for socket_errors_to_ignore in the first place, but  the fix for this error message is described here:
https://bitbucket.org/cherrypy/cherrypy/issues/1114/got-socket_errors_to_ignore-on-windows

socket_errors_to_ignore has to be added to the **all** list that starts on line 71

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1376

**Comment by hbhuwania** [comment]
I am observing same error message. Cherrpy version being used is 3.8 with python 2.7. Any suggestions on what is the fix for the same?

**Comment by webknjaz** [comment]
That version is unsupported. The right thing to do is to upgrade to the latest one. I suppose it should've been fixed ages ago.

**Comment by hbhuwania** [comment]
Sure. I understand we are working on a very old cherrypy version and there is a patch that will fix:
AttributeError: 'module' object has no attribute 'socket_errors_to_ignore'


But do you know what exact cherrypy version to migrate to which fixes below socket.error() (we are using python2.7 and for now have limitations migrating to python3). We see these worker thread exiting with below exception

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1525, in run
    conn.communicate()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1407, in communicate
    req.simple_response("500 Internal Server Error")
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 904, in simple_response
    self.conn.wfile.sendall("".join(buf))
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 105, in sendall

  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1010, in sendall
    bytes_sent = self.send(data)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 109, in send
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 78, in _safe_call
    raise socket.error(errnum)
error: -1

AttributeError("'module' object has no attribute 'socket_errors_to_ignore'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1343, in communicate
    req.parse_request()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 610, in parse_request
    success = self.read_request_line()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 643, in read_request_line
    request_line = self.rfile.readline()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 301, in readline
    data = self.rfile.readline(256)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1163, in readline
    data = self.recv(self._rbufsize)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 101, in recv
    return self._safe_call(True, super(SSL_fileobject, self).recv, size)
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/ssl_pyopenssl.py", line 76, in _safe_call
    if is_reader and errnum in wsgiserver.socket_errors_to_ignore:
AttributeError: 'module' object has no attribute 'socket_errors_to_ignore'
Exception in thread CP Server Thread-4:

**Comment by webknjaz** [comment]
CherryPy v17 stream is the last major version supporting Python 2.7. The general recommendation is to use it if you can't have it under Python 3.

**Comment by hbhuwania** [comment]
Sure. Makes sense. Eventually that is the plan.
One general query I had was why after these worker threads exit with an exception; we see open file descriptors for the cherrypy process keep on increasing. (fyi: We have processes sending cherrypy service curl request periodically) and ultimately we reach ulimit set (i.e 1024). Is there a socket cleanup routine missing somewhere in cherrypy code and if there is a version I can look at for the fix. Also after the fd limit is reached logs are flooded with 

Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1968, in start
    self.tick()
  File "/usr/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2020, in tick
    s, addr = self.socket.accept()
  File "<string>", line 4, in accept
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1972, in accept
  File "/usr/lib/python2.7/socket.py", line 206, in accept
error: [Errno 24] Too many open files

**Comment by webknjaz** [comment]
That code now lives in Cheroot (for years) and has been refactored a few times so it's hard to say atm.
