### ISSUE TITLE
exception from wsgiserver3

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1383]
Originally reported by: **Ram Bhamidipaty (Bitbucket: [redcordnow](http://bitbucket.org/redcordnow), GitHub: Unknown)**

----------------------------------------

I am getting an exception from cherrypy:

I am running cherrypy 3.8.0

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 1058, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 584, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.4/site-packages/cherrypy/wsgiserver/wsgiserver3.py", line 653, in read_request_line
    if NUMBER_SIGN in path:
TypeError: argument of type 'NoneType' is not iterable
```

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1383

**Comment by jaraco** [comment]
Fixed in 6a12dc28ce77 and released as 3.8.1.
