### ISSUE TITLE
wsgiserver3 socket.error 10058 on server shutdown

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1403]
Originally reported by: **Lindsay Stevens (Bitbucket: [lindsay-stevens-kirby](http://bitbucket.org/lindsay-stevens-kirby), GitHub: @lindsay-stevens)**

---

Following my comment on issue #1342. Using the same test setup as described there, if I make a request to 127.0.0.1:8080 then immediately issue a keyboard interrupt to shut down the server, a socket error will bubble up from wsgiserver3. 

It seems like a edge case that's so remote it's almost off the edge, but since it cause a Traceback I thought I'd report it. Typical result is copied below. 

```
[22/Jan/2016:18:18:32] ENGINE Console event 0: shutting down bus
[22/Jan/2016:18:18:32] ENGINE Removed handler for console events.
[22/Jan/2016:18:18:32] ENGINE Bus STOPPING
[22/Jan/2016:18:18:40] ENGINE socket.error 10058
Traceback (most recent call last):
  File "C:\Users\Lstevens\Documents\repos\cherrytest\lib\site-packages\cherrypy
  \wsgiserver\wsgiserver3.py", line 1063, in communicate
    req.parse_request()
  File "C:\Users\Lstevens\Documents\repos\cherrytest\lib\site-packages\cherrypy
  \wsgiserver\wsgiserver3.py", line 585, in parse_request
    success = self.read_request_line()
  File "C:\Users\Lstevens\Documents\repos\cherrytest\lib\site-packages\cherrypy
  \wsgiserver\wsgiserver3.py", line 618, in read_request_line
    request_line = self.rfile.readline()
  File "C:\Users\Lstevens\Documents\repos\cherrytest\lib\site-packages\cherrypy
  \wsgiserver\wsgiserver3.py", line 276, in readline
    data = self.rfile.readline(256)
  File "C:\Python351x64\lib\_pyio.py", line 509, in readline
    b = self.read(nreadahead())
  File "C:\Python351x64\lib\_pyio.py", line 493, in nreadahead
    readahead = self.peek(1)
  File "C:\Python351x64\lib\_pyio.py", line 1062, in peek
    return self._peek_unlocked(size)
  File "C:\Python351x64\lib\_pyio.py", line 1069, in _peek_unlocked
    current = self.raw.read(to_read)
  File "C:\Python351x64\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
BrokenPipeError: [WinError 10058] A request to send or receive data was disallow
ed because the socket had already been shut down in that direction with a previo
us shutdown call

[22/Jan/2016:18:18:42] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer((
'127.0.0.1', 8080)) shut down
[22/Jan/2016:18:18:42] ENGINE Stopped thread 'Autoreloader'.
[22/Jan/2016:18:18:42] ENGINE Handler for console events already off.
[22/Jan/2016:18:18:42] ENGINE Stopped thread '_TimeoutMonitor'.
[22/Jan/2016:18:18:42] ENGINE Bus STOPPED
[22/Jan/2016:18:18:42] ENGINE Bus EXITING
[22/Jan/2016:18:18:42] ENGINE Waiting for child threads to terminate...
[22/Jan/2016:18:18:42] ENGINE Bus EXITED
```

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1403

**Comment by webknjaz** [comment]
ref: @lindsay-stevens

**Comment by webknjaz** [comment]
Hi @lindsay-stevens,
could you please confirm that this is still reproducible?

**Comment by webknjaz** [comment]
Note: the code has moved to https://github.com/cherrypy/cheroot/blob/master/cheroot/server.py#L948, so this issue may need moving to [cheroot repo](https://github.com/cherrypy/cheroot).

**Comment by webknjaz** [comment]
This looks similar to #1351 and may have similar solution
