### ISSUE TITLE
Server.satistics failing for wsgiserver3.py

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1414]
Originally reported by: **Anonymous**

---

When server.statistics is set to collect statistics with the inbuilt wsgiserver,  we see the following exception:

Exception in thread CP Server Thread-3:
[20/Apr/2016:14:21:56] ENGINE Bus STARTED
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 911, in _bootstrap_inner
    self.run()
  File "C:\Users\devbevanl\cherryapi\venv\lib\site-packages\cherrypy\wsgiserver\wsgiserver3.py", line 1256, in run
    self.bytes_read += self.conn.rfile.bytes_read
AttributeError: 'BufferedReader' object has no attribute 'bytes_read'

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1414

**Comment by polotek** [comment]
Is there a plan to fix this? It looks like the problem is that BufferedReader is a wrapper around a connection and doesn't have the `bytes_read` property. I could think of a couple of ways to approach this, and I'm willing to work up a PR. Would you accept it? Any guidance is appreciated.

**Comment by webknjaz** [comment]
Hello,

First of all it would be nice to see minimal snippet for reproducing the issue. Keep in mind, that now `wsgiserver3.py` and `wsgiserver2.py` are megred into a single module working under both Python 2 and Python 3. Please confirm that this issue still exists in supported Python 3 environment for the latest CherryPy version.

Second, if the problem is still worth fixing it, PR should contain:
- [ ] Documentation, describing the feature (as currently it's not well-documented)
- [ ] Bugfix itself
- [ ] Tests proving it works for all supported Python versions (2.7-3.6)

Finally, we'll point out any issues in your PR to let you fix them before approval and there are a couple of external checks (like Travis CI) helping you to get an idea whether you break anything with your PR.
