### ISSUE TITLE
When installing cherrypy under python3, it flunks self test

### ISSUE THREAD

**Issue by jeffsilverm** [cherrypy/cherrypy#1446]
Second, the self-test flunks, because one of the files was no converted to python3 and throws an exception:

```
jeffs@jeff-desktop:~/Downloads/cherrypy-master$ sudo python3 setup.py check
running check
jeffs@jeff-desktop:~/Downloads/cherrypy-master$ python3 setup.py test
running test
running egg_info
writing dependency_links to CherryPy.egg-info/dependency_links.txt
error: [Errno 13] Permission denied: 'CherryPy.egg-info/dependency_links.txt'
jeffs@jeff-desktop:~/Downloads/cherrypy-master$ sudo python3 setup.py test
running test
running egg_info
writing CherryPy.egg-info/PKG-INFO
writing requirements to CherryPy.egg-info/requires.txt
writing dependency_links to CherryPy.egg-info/dependency_links.txt
writing top-level names to CherryPy.egg-info/top_level.txt
reading manifest file 'CherryPy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'CherryPy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 155, in <module>
    main()
  File "setup.py", line 151, in main
    setuptools.setup(**setup_params)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/usr/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/home/jeffs/Downloads/cherrypy-master/cherrypy/wsgiserver/wsgiserver2.py", line 1019
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
jeffs@jeff-desktop:~/Downloads/cherrypy-master$ 
```

**Comment by jaraco** [comment]
Thanks Jeff, but `setup.py test` isn't a supported mode for running CherryPy tests. Tests should be run using `nosetests -s` as seen in the `.travis.yml` and probably docs.

**Comment by webknjaz** [comment]
@jeffsilverm JFYI not it works this way as well
