### ISSUE TITLE
cherrypy ssl support not working

### ISSUE THREAD

**Issue by amraks** [cherrypy/cherrypy#1448]
I compile my python code into a binary using pyinstaller in a  debian wheezy 64 bit chroot environment.

Have the latest cherrypy (6.0.1). When I run the binary with ssl support enabled I see following traceback

[17/Jun/2016:16:07:32] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7fc25c5672d0>>
Traceback (most recent call last):
  File "/home/run_pyinstaller/build/egnyte_local_cloud_client/out00-PYZ.pyz/cherrypy.process.wspbus", line 203, in publish
  File "/home/run_pyinstaller/build/egnyte_local_cloud_client/out00-PYZ.pyz/cherrypy._cpserver", line 167, in start
  File "/home/run_pyinstaller/build/egnyte_local_cloud_client/out00-PYZ.pyz/cherrypy._cpserver", line 158, in httpserver_from_self
  File "/home/run_pyinstaller/build/egnyte_local_cloud_client/out00-PYZ.pyz/cherrypy._cpwsgi_server", line 60, in __init__
  File "/home/run_pyinstaller/build/egnyte_local_cloud_client/out00-PYZ.pyz/cherrypy.wsgiserver.wsgiserver2", line 2191, in get_ssl_adapter_class
ImportError: No module named ssl_builtin

Here is the relevant cherrypy config file

[global]
server.socket_host: '0.0.0.0'
server.socket_port: 8807
server.ssl_module : 'builtin'
server.ssl_certificate : '/home/xyz/certs/cert1.pem'
server.ssl_private_key : '/home/xyz/certs/privkey1.pem'
log.screen: True

I cannot use pyopenssl since it has enum34 as a dependency which clashes with enum package.

**Comment by amraks** [comment]
Hi, Can anyone provide a response? Thanks

**Comment by jaraco** [comment]
Does your application work when not run in pyinstaller? If so, then the issue lies with pyinstaller. It's possible a hook could be added to CherryPy to ensure that programmatically-imported modules are detected by pyinstaller. The `keyring` project does this. Would you try adding that hook for the relevant missing module and see if that corrects the condition?

**Comment by amraks** [comment]
Hello Jason, I wrote some sample script which I run on 64-bit CentOS with 'server.ssl_module' set to 'builtin'. This works.

But when I build my application with pyinstaller (with server.ssl_module set to builtin in the configuration file), cherrypy complains about pyopenssl.

I guess the hook that you mention would be applicable if I were using some third party module which pyinstaller does not recognize. But in this case I want cherrypy to use the standard ssl module.

Thanks for the help

Edit: Let me try passing ssl as a hidden import to pyinstaller. I will update this thread.

**Comment by amraks** [comment]
Hi Jason,

I compiled following code with pyinstaller.

sss.py

import cherrypy

config = {
  'global' : {
    'server.socket_host' : '0.0.0.0',
    'server.socket_port' : 8888,
    'server.thread_pool' : 8,
    'server.ssl_module'            : 'builtin',
    'server.ssl_certificate'       : '/certs/cert.pem',
    #'server.ssl_certificate_chain' : '/path/to/certs/ssl123_ca_bundle.pem',
    'server.ssl_private_key'       : '/certs/key.pem'
  }
}
class App:

  @cherrypy.expose
  def index(self):
    return '<em>Is this secure?</em>'

if **name** == '**main**':
  cherrypy.quickstart(App(), '/', config)

Compile command: pyinstaller --hidden-import=ssl sss.py
Compile env: 64-bit Debian wheezy

When I run it I see following:

Runtime env: Debian wheezy 64-bit chroot

root@localhost:/sss# export LD_LIBRARY_PATH=/sss && ./sss
[22/Jun/2016:13:58:06] ENGINE Listening for SIGHUP.
[22/Jun/2016:13:58:06] ENGINE Listening for SIGTERM.
[22/Jun/2016:13:58:06] ENGINE Listening for SIGUSR1.
[22/Jun/2016:13:58:06] ENGINE Bus STARTING
[22/Jun/2016:13:58:06] ENGINE Started monitor thread '_TimeoutMonitor'.
[22/Jun/2016:13:58:06] ENGINE Started monitor thread 'Autoreloader'.
[22/Jun/2016:13:58:06] ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/home/run_pyinstaller/pyinst/build/sss/out00-PYZ.pyz/cherrypy.process.servers", line 73, in _start_http_thread
  File "/home/run_pyinstaller/pyinst/build/sss/out00-PYZ.pyz/cherrypy.wsgiserver", line 1588, in start
  File "/home/run_pyinstaller/pyinst/build/sss/out00-PYZ.pyz/cherrypy.wsgiserver", line 1624, in bind
**ImportError: You must install pyOpenSSL to use HTTPS.**

Could you help me out here? Thanks

Edit: Tried with pyinstaller 2.1 and 3.2

**Comment by amraks** [comment]
I upgraded cherrypy to 4.0.0 and compiled the binary with pyinstaller. Now I see following traceback

[22/Jun/2016:17:11:29] ENGINE Listening for SIGHUP.
[22/Jun/2016:17:11:29] ENGINE Listening for SIGTERM.
[22/Jun/2016:17:11:29] ENGINE Listening for SIGUSR1.
[22/Jun/2016:17:11:29] ENGINE Bus STARTING
[22/Jun/2016:17:11:29] ENGINE Started monitor thread 'Autoreloader'.
[22/Jun/2016:17:11:29] ENGINE Started monitor thread '_TimeoutMonitor'.
[22/Jun/2016:17:11:29] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f33d3042ed0>>
Traceback (most recent call last):
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy.process.wspbus", line 203, in publish
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy._cpserver", line 167, in start
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy._cpserver", line 158, in httpserver_from_self
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy._cpwsgi_server", line 60, in __init__
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy.wsgiserver.wsgiserver2", line 2208, in get_ssl_adapter_class
ImportError: No module named ssl_builtin

[22/Jun/2016:17:11:29] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy.process.wspbus", line 241, in start
  File "/home/run_pyinstaller/pyins/build/sss/out00-PYZ.pyz/cherrypy.process.wspbus", line 221, in publish
ChannelFailures: ImportError('No module named ssl_builtin',)

Env:
build in 64-bit debian wheezy
run on 64-bit debian wheezy
cherrypy 4.0.0
pyinstaller 2.1
python 2.7.10
ssl module specified in config file: builtin

Edit: python does have ssl

root@drtg:~# python
Python 2.7.10 (default, Aug 12 2015, 13:54:23) 
[GCC 4.7.2] on linux2

> > > import ssl

**Comment by jaraco** [comment]
The issue is probably that pyinstaller is omitting the `cherrypy.wsgiserver.ssl_builtin` module from the build, as that module is loaded programmatically by the `get_ssl_adapter_class` function in wsgiserver.

What happens if you add a `hook-cherrypy.wsgiserver.py` file to the root of the cherrypy project with this content:

```
# Used by pyinstaller to expose hidden imports

hiddenimports = [
    'cherrypy.wsgiserver.ssl_builtin',
]
```

I'm not sure how pyinstaller would discover that hook, but that's similar to what someone has contributed in the keyring project. You could probably include something similar in your pyinstaller builder as well.

**Comment by jaraco** [comment]
The issue is probably that pyinstaller is omitting the `cherrypy.wsgiserver.ssl_builtin` module from the build, as that module is loaded programmatically by the `get_ssl_adapter_class` function in wsgiserver.

What happens if you add a `hook-cherrypy.wsgiserver.py` file to the root of the cherrypy project with this content:

```
# Used by pyinstaller to expose hidden imports

hiddenimports = [
    'cherrypy.wsgiserver.ssl_builtin',
]
```

I'm not sure how pyinstaller would discover that hook, but that's similar to what someone has contributed in the keyring project. You could probably include something similar in your pyinstaller builder as well.

**Comment by amraks** [comment]
Fantastic! That works. Thanks a ton.

I am closing out this issue.

**Comment by rsb-developer** [comment]
It appears for more recent versions, you must include the hidden import of "cheroot.ssl.builtin" 
`--hidden-import=cheroot.ssl.builtin`
