### ISSUE TITLE
test_refleaks fails regularly on MacOS

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1474]
I'm running the tests on Python 3.5.2 on OS X 10.11.6. The test_refleaks fails regularly with output like this:

```python-traceback
$ ~/.envs/cherrypy/bin/nosetests -s cherrypy.test.test_refleaks
test_threadlocal_garbage (cherrypy.test.test_refleaks.ReferenceTests) ... Exception in thread Thread-18:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-25:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

Exception in thread Thread-27:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer






Exception in thread Thread-29:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 43, in getpage
    response = c.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer


FAIL
test_gc (cherrypy.test.test_refleaks.ReferenceTests) ... ok

======================================================================
FAIL: test_threadlocal_garbage (cherrypy.test.test_refleaks.ReferenceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_refleaks.py", line 64, in test_threadlocal_garbage
    self.assertEqual(next(success), ITERATIONS)
AssertionError: 12 != 25
-------------------- >> begin captured logging << --------------------
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Listening for SIGTERM.
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Listening for SIGHUP.
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Listening for SIGUSR1.
cherrypy.test.helper: INFO: Python version used to run this test script: 3.5.2
cherrypy.test.helper: INFO: CherryPy version: 4.0.0
cherrypy.test.helper: INFO: HTTP server version: HTTP/1.1
cherrypy.test.helper: INFO: PID: 68132
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Bus STARTING
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Started monitor thread '_TimeoutMonitor'.
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Serving on http://127.0.0.1:54583
cherrypy.error: INFO: [21/Aug/2016:09:37:45] ENGINE Bus STARTED
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:45] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:45] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:45] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:45] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:45] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
cherrypy.access.4352212608: INFO: 127.0.0.1 - - [21/Aug/2016:09:37:46] "GET / HTTP/1.1" 200 12 "" ""
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 0.600s

FAILED (failures=1)
```

The number of successes varies. I see it typically between 5 and 10, but I've seen it as high as 17, but it's never reached full success (25) on my machine.

~Perhaps [this unanswered question](http://stackoverflow.com/questions/37899955/connection-reset-by-peer-on-mac-but-not-windows) is relevant.~ Here's [another question](http://stackoverflow.com/questions/29993807/connection-reset-by-peer-when-testing-web-server-on-different-computers) precisely describing our issue.

**Comment by jaraco** [comment]
Following the hint about the socket backlog, and reading answers to [this question](http://stackoverflow.com/questions/2444459/python-sock-listen), I found if I change the `_cp_server.Server.socket_queue_size` to 25, the tests stop failing. Even at 24, the tests consistently fail (with exactly one "connection reset by peer" message).

**Comment by jaraco** [comment]
I'm not sure what the solution is here. Should CherryPy be able to accept these connections more quickly? Or should we bump the backlog? If bumping the backlog, should it be for this invocation of the server or for CherryPy in general? Why does the issue only affect Mac? For now, I'm going to disable the test on MacOs.

**Comment by webknjaz** [comment]
BTW, I've just mentioned this doc https://docs.travis-ci.com/user/multi-os/
I think we could extend environments coverage in Travis CI this way

**Comment by webknjaz** [comment]
Possibly related: https://github.com/cherrypy/cherrypy/issues/1839
