### ISSUE TITLE
Getting cherrypy.TimeoutError

### ISSUE THREAD

**Issue by rbjorklin** [cherrypy/cherrypy#1501]
I'm using saltstack and have some long running jobs that seem to throw timeout errors after 300 seconds. Pretty sure not being able to specify [this](https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_cprequest.py#L875) is what's causing me issues.

Stacktrace:

```
  [ERROR   ] [15/Sep/2016:13:05:35]  Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 169, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 96, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 379, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 222, in __init__
    self.run()
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpwsgi.py", line 320, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 603, in run
    raise cherrypy.TimeoutError()
  TimeoutError
```

**Comment by jaraco** [comment]
A google search for `cherrypy timeout` took me straight to the [docs for response timeouts](http://docs.cherrypy.org/en/latest/advanced.html#response-timeouts), which suggests how change the timeout or disable timeouts.

**Comment by jaraco** [comment]
If you have questions about those docs or encounter difficulty implementing it in your saltstack app, do feel free to add follow-up questions.
