### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by stenci** [cherrypy/cherrypy#1505]
This morning one of our internal servers was not working (restarting it fixed the problem). Below you can see two excerpt from the log file. 

I don't like to ignore a problem that puts down a server (even if that server has been working without problems for one year).

Can you please tell me if there is something I should investigate?  

The production server that failed and produced the tracebacks below has CherryPy 4.0.0. The development server that I'm getting ready to deploy has the 7.1.0. It runs on Windows 7 Pro (because it interacts with some old Windows software that only runs on Windows 7).

The first error logged this morning was this:

```
[23/Sep/2016:06:38:02] HTTP 
Traceback (most recent call last):
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cprequest.py", line 663, in respond
    self.body.process()
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 540, in process
    proc(self)
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 157, in process_urlencoded
    value = unquote_plus(atoms[1]).decode(charset)
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 124, in unquote_plus
    atoms = bs.split(ntob('%'))
MemoryError
```

Then there were many errors like this:

```
[23/Sep/2016:07:10:49] HTTP 
Traceback (most recent call last):
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cprequest.py", line 663, in respond
    self.body.process()
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 996, in process
    super(RequestBody, self).process()
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 540, in process
    proc(self)
  File "C:\Anaconda34-32\lib\site-packages\cherrypy\_cpreqbody.py", line 152, in process_urlencoded
    atoms = pair.split(ntob('='), 1)
MemoryError
```

**Comment by webknjaz** [comment]
@stenci 
It looks the cherrypy process just ran out of memory. I don't know the reason, but you should troubleshoot memory consumption. Perhaps there were too many requests, which lead to too many in-memory data (requests bodies).

I see you use 32-bit Python, but do you run x86 OS as well? If you'll install 64-bit Python, the memory limit will increase. See [this SO answer](http://stackoverflow.com/a/4441958/595220).

P.S. Just to clarify, the cherrypy process **was running**, but **didn't serve requests**? Right? Were there any other requests served well during the outage? Or it was completely down?

P.P.S. For linux there's a tool called `monit`, it is able to monitor processes availability and restart them if needed. Maybe you should use similar approach as well. Still don't forget about monitoring systems.

P.P.P.S. If I were you, I'd run just a simple microservice exposing your win app's API via HTTP and run everything else separately under true *NIX

**Comment by webknjaz** [comment]
@stenci and if the process was running, what was the HTTP response code and the app behaviour from the client perspective?

**Comment by webknjaz** [comment]
@jaraco Shouldn't it result in HTTP 500? Simple grep against the repo found no `MemoryError` exception handlers.

**Comment by stenci** [comment]
@webknjaz 
Thanks, I will look into memory problems. You can close this issue.

Here are more details.

The app imports DXF drawings, nests them into sheets of material, creates the G code for the CNC machine and the drawing of the whole program. Something similar to [this](https://en.wikipedia.org/wiki/Nesting_%28process%29). If the DXF drawings don't exist it will ask an old 32 bit CAD software to generate them using `win32com.client`, that's why Python is 32 bit. I already started splitting the big app into smaller apps, and one of them takes care of the CAD. But since they are all for internal use and we use Windows for all our software, I didn't think of using ***nix (yet). I will look into that, thanks.

On the client side there is an Excel VBA macro that sends the list of drawings to the server and polls every second waiting for the job to be finished. A job with 2-3 drawings can finish in half second, a larger job like the one running this morning with 1500 drawings can take hours.

They called me while I was in the car. I told them to shutdown and restart the server, so I don't know anything more than what the log says.

The app caches the DXF drawings (with some shapely paths) used in the last 24 hours in a list. Very likely 1500 drawings of this job plus whatever was done yesterday are responsible of filling up the memory. 

This is the largest nesting done in one year. I will add some memory usage monitoring in that cache and, if the problem is there, do something smarter than a list with a 24 hour expiration timestamp.

**Comment by webknjaz** [comment]
Well, I believe 64-bit process should be able to interact with 32-bit one. https://msdn.microsoft.com/en-us/library/windows/desktop/aa384203(v=vs.85).aspx
But if it's the win app eating all the memory I think adding RAM will help.

P.S. I'll keep this issue open for a while to check with @jaraco whether we should handle `MemoryError`s in a nicer way.

**Comment by webknjaz** [comment]
@jaraco?

**Comment by webknjaz** [comment]
@jaraco?

**Comment by webknjaz** [comment]
@jaraco what is our strategy regarding `MemoryError`?

**Comment by jaraco** [comment]
First things first, I want to apologize for the Unix shaming. Python and CherryPy embrace non-Unix systems, especially Windows. So unless there's specifically a reason why the code could not run on Windows systems (e.g. requires fork or fnctl), CherryPy will try to support it.

As for the MemoryError, I'm not sure CherryPy could even do anything about it.

> Shouldn't it result in HTTP 500?

The problem is that if you're a process that no longer has access to allocate new memory, you can't invoke any operations that require memory, such as constructing a response.

I could imagine, however, a scenario where on startup CherryPy might pre-allocate all of the structures necessary to return a 500 response in the event of a MemoryError and then catch that error in the server and provide some minimal response. I'm not sure if such an approach is even feasible at the Python level, but I'd welcome at attempt to demonstrate it.

**Comment by webknjaz** [comment]
@jaraco thanks for great suggestions! I'll try investigating the possibility of memory pre-allocation :)
