### ISSUE TITLE
Google App Engine - Last running version 8.1.0

### ISSUE THREAD

**Issue by immoads-gerold-penz** [cherrypy/cherrypy#1512]
Hello!

Version 8.1.2 doesn't run on Google App Engine. Last functional version is 8.1.0. 

```
Traceback on local development environment:
`ERROR    2016-10-13 13:39:37,435 wsgi.py:263] 
Traceback (most recent call last):
  File "/home/gerold/bin/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/gerold/bin/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/gerold/bin/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/gerold/PROG_GAE/urlshortener/development/application/__init__.py", line 9, in <module>
    import cherrypy
  File "/home/gerold/PROG_GAE/urlshortener/development/application/ziplibs/cherrypy.zip/cherrypy/__init__.py", line 83, in <module>
    from cherrypy import _cpserver
  File "/home/gerold/PROG_GAE/urlshortener/development/application/ziplibs/cherrypy.zip/cherrypy/_cpserver.py", line 11, in <module>
  File "/home/gerold/PROG_GAE/urlshortener/development/application/ziplibs/cherrypy.zip/cherrypy/process/__init__.py", line 13, in <module>
  File "/home/gerold/PROG_GAE/urlshortener/development/application/ziplibs/cherrypy.zip/cherrypy/process/wspbus.py", line 64, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 10, in <module>
    from _ctypes import Union, Structure, Array
  File "/home/gerold/bin/google_appengine/google/appengine/tools/devappserver2/python/sandbox.py", line 963, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named _ctypes
INFO     2016-10-13 13:39:37,441 module.py:788] default: "GET / HTTP/1.1" 500 -`
```

Traceback from the Google App Engine:
`Traceback (most recent call last): File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle handler = _config_handle.add_wsgi_middleware(self._LoadHandler()) File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler handler, path, err = LoadObject(self._handler) File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject obj = __import__(path[0]) File "/base/data/home/apps/e~immoads-urls/1.396308998291540879/application/__init__.py", line 9, in <module> import cherrypy File "/base/data/home/apps/e~immoads-urls/1.396308998291540879/application/ziplibs/cherrypy.zip/cherrypy/__init__.py", line 83, in <module> from cherrypy import _cpserver File "/base/data/home/apps/e~immoads-urls/1.396308998291540879/application/ziplibs/cherrypy.zip/cherrypy/_cpserver.py", line 11, in <module> File "/base/data/home/apps/e~immoads-urls/1.396308998291540879/application/ziplibs/cherrypy.zip/cherrypy/process/__init__.py", line 13, in <module> File "/base/data/home/apps/e~immoads-urls/1.396308998291540879/application/ziplibs/cherrypy.zip/cherrypy/process/wspbus.py", line 64, in <module> File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/ctypes/__init__.py", line 10, in <module> from _ctypes import Union, Structure, Array ImportError: No module named _ctypes`

I have no idea.

Regards,
Gerold

**Comment by jaraco** [comment]
According to [this answer](http://stackoverflow.com/a/6523777/70170), GAE doesn't supply the standard ctypes module. It wasn't intentional to drop support for GAE, but we have inadvertently.

**Comment by jaraco** [comment]
That behavior was added here - 2c00069684e, which was included in 8.1.1, confirming your findings.

**Comment by jaraco** [comment]
@webknjaz Can you envision an implementation of the autoreloader that is disabled (or doesn't honor interpreter flags) on platforms where ctypes isn't available?

I wonder alternatively if the recently-released GAE for Python 3 supports ctypes. If so, I'd be inclined to say we won't fix this and will expect GAE users to migrate to Python 3 or use older CherryPy versions.

**Comment by webknjaz** [comment]
@jaraco I think it's enough to trap `ImportError` and fallback it to `None`.
This will cause `AttributeError` in `_get_true_argv()`, which is already being processed for win32: https://github.com/cherrypy/cherrypy/blob/427261aa1748657f149f62da90a09938856cf327/cherrypy/process/wspbus.py#L423

**Comment by webknjaz** [comment]
@immoads-gerold-penz thanks for your report, the next version of cherrypy should have this fixed now :)

**Comment by immoads-gerold-penz** [comment]
Thank you @jaraco and @webknjaz!
I have tried it. CherryPy is running again on Google App Engine. :-)
Regards, Gerold
