### ISSUE TITLE
Tutorials - @cherrypy.expose on class

### ISSUE THREAD

**Issue by matt-paul** [cherrypy/cherrypy#1520]
In tutorials 7 and 8, we are told to expose the class ie

```
@cherrypy.expose'
class StringGeneratorWebService(object):
```

This however does not seem to work, but adding @cherrypy.expose on to the individual methods does.

**Comment by jaraco** [comment]
Not in my experience. I copied tutorial 7 to a file, ran it with a late version of CherryPy, and it was working for me (at least responding to GET and POST requests).

Aha. I suspect the issue is that you're using an old version of Python (Python 2.7 or earlier). According to [the PEP](https://www.python.org/dev/peps/pep-3129/), support for class decorators was not added until Python 3. I suggest instead using Python 3.

I'll update the tutorials to indicate this expectation and a workaround.

**Comment by jaraco** [comment]
I've reverted the change as apparently the @expose decorator should work on Python 2.6+, which is what CherryPy supports. Re-reading the report, the issue seems to be not that the expose decorator is on the class but that the methods themselves need to be exposed.

**Comment by jaraco** [comment]
Using Python 2.6, I ran the tutorial and it does seem to be handling the request:

```
$ cat docs/tutorial-7.py
import random
import string

import cherrypy


@cherrypy.expose
class StringGeneratorWebService(object):

   @cherrypy.tools.accept(media='text/plain')
   def GET(self):
       return cherrypy.session['mystring']

   def POST(self, length=8):
       some_string = ''.join(random.sample(string.hexdigits, int(length)))
       cherrypy.session['mystring'] = some_string
       return some_string

   def PUT(self, another_string):
       cherrypy.session['mystring'] = another_string

   def DELETE(self):
       cherrypy.session.pop('mystring', None)


if __name__ == '__main__':
   conf = {
       '/': {
           'request.dispatch': cherrypy.dispatch.MethodDispatcher(),
           'tools.sessions.on': True,
           'tools.response_headers.on': True,
           'tools.response_headers.headers': [('Content-Type', 'text/plain')],
       }
   }
   cherrypy.quickstart(StringGeneratorWebService(), '/', conf)
```

```
$ cp ~/p/six/six.py .
$ PYTHONPATH=. python2.6 docs/tutorial-7.py
[16/Dec/2016:14:49:44] ENGINE Listening for SIGUSR1.
[16/Dec/2016:14:49:44] ENGINE Listening for SIGTERM.
[16/Dec/2016:14:49:44] ENGINE Listening for SIGHUP.
[16/Dec/2016:14:49:44] ENGINE Bus STARTING
[16/Dec/2016:14:49:44] ENGINE Started monitor thread '_TimeoutMonitor'.
[16/Dec/2016:14:49:44] ENGINE Started monitor thread 'Autoreloader'.
[16/Dec/2016:14:49:44] ENGINE Serving on http://127.0.0.1:8080
[16/Dec/2016:14:49:44] ENGINE Bus STARTED
[16/Dec/2016:14:49:47] ENGINE Started monitor thread 'Session cleanup'.
[16/Dec/2016:14:49:47] HTTP 
Traceback (most recent call last):
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "docs/tutorial-7.py", line 12, in GET
    return cherrypy.session['mystring']
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/__init__.py", line 254, in __getitem__
    return child[key]
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/lib/sessions.py", line 308, in __getitem__
    return self._data[key]
KeyError: 'mystring'
[16/Dec/2016:14:49:47] HTTP 
Request Headers:
  CACHE-CONTROL: max-age=0
  COOKIE: session_id=a0b4dff66b079ae55721a429e44040b57cae4e86
  UPGRADE-INSECURE-REQUESTS: 1
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: gzip, deflate
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  HOST: localhost:8080
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
127.0.0.1 - - [16/Dec/2016:14:49:47] "GET / HTTP/1.1" 500 1648 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0"
^C[16/Dec/2016:14:50:33] ENGINE Keyboard Interrupt: shutting down bus
[16/Dec/2016:14:50:33] ENGINE Bus STOPPING
[16/Dec/2016:14:50:33] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[16/Dec/2016:14:50:33] ENGINE Stopped thread '_TimeoutMonitor'.
[16/Dec/2016:14:50:33] ENGINE Stopped thread 'Autoreloader'.
[16/Dec/2016:14:50:33] ENGINE Stopped thread 'Session cleanup'.
[16/Dec/2016:14:50:33] ENGINE Bus STOPPED
[16/Dec/2016:14:50:33] ENGINE Bus EXITING
[16/Dec/2016:14:50:33] ENGINE Bus EXITED
[16/Dec/2016:14:50:33] ENGINE Waiting for child threads to terminate...
```

Which suggests to me that the `expose` decorator is not only valid syntax but is being honored by cherrypy. I'm using Python 2.6.9.

If you still think this is an issue, feel free to dig deeper and provide more detail on what is not working an why. If it's due to older versions of Python 2.6, I'd say that's not supported. If it's due to Python prior to 2.6, that's definitely not supported.
