### ISSUE TITLE
Fix imports in module mode

### ISSUE THREAD

**Issue by webknjaz** [cherrypy/cherrypy#1546]
While removing `cherryd` script (003aa4ec) I've found out that doing imports in daemon mode fail for Python <= 3.3:
https://travis-ci.org/cherrypy/cherrypy/jobs/190220415
```log
$ .tox/py33/bin/python3.3 -b -m cherrypy -c ~/src/cherrypy/cherrypy/test/test.conf -p ~/src/cherrypy/cherrypy/test/test.pid -d

$ tail -n50 ~/src/cherrypy/cherrypy/test/test.error.log
...
[09/Jan/2017:15:38:09] ENGINE Listening for SIGUSR1.
[09/Jan/2017:15:38:09] ENGINE Listening for SIGTERM.
[09/Jan/2017:15:38:09] ENGINE Listening for SIGHUP.
[09/Jan/2017:15:38:09] ENGINE Bus STARTING
[09/Jan/2017:15:38:09] ENGINE Forking once.
[09/Jan/2017:15:38:09] ENGINE Forking twice.
[09/Jan/2017:15:38:09] ENGINE Daemonized to PID: 13872
[09/Jan/2017:15:38:09] ENGINE Started monitor thread '_TimeoutMonitor'.
[09/Jan/2017:15:38:09] ENGINE PID 13872 written to '~/src/cherrypy/cherrypy/test/test.pid'.
[09/Jan/2017:15:38:09] ENGINE Started monitor thread 'Autoreloader'.
[09/Jan/2017:15:38:09] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f21ab943a50>>
Traceback (most recent call last):
  File "./cherrypy/process/wspbus.py", line 216, in publish
    output.append(listener(*args, **kwargs))
  File "./cherrypy/_cpserver.py", line 176, in start
    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "./cherrypy/_cpserver.py", line 166, in httpserver_from_self
    from cherrypy import _cpwsgi_server
ImportError: cannot import name _cpwsgi_server

[09/Jan/2017:15:38:09] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "./cherrypy/process/wspbus.py", line 254, in start
    self.publish('start')
  File "./cherrypy/process/wspbus.py", line 234, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: ImportError('cannot import name _cpwsgi_server',)

[09/Jan/2017:15:38:09] ENGINE Bus STOPPING
[09/Jan/2017:15:38:09] ENGINE HTTP Server None already shut down
[09/Jan/2017:15:38:09] ENGINE Stopped thread 'Autoreloader'.
[09/Jan/2017:15:38:09] ENGINE Stopped thread '_TimeoutMonitor'.
[09/Jan/2017:15:38:09] ENGINE Bus STOPPED
[09/Jan/2017:15:38:09] ENGINE Bus EXITING
[09/Jan/2017:15:38:09] ENGINE PID file removed: '~/src/cherrypy/cherrypy/test/test.pid'.
[09/Jan/2017:15:38:09] ENGINE Bus EXITED
```

**Comment by jaraco** [comment]
One question that comes to mind - why is it that the cwd is relevant to the imports? It shouldn't be, as the environment (`.tox/py33` in your example) should have had cherrypy installed in editable mode (tox.ini `usedevelop = True`), so the cherrypy package and its sub packages should all be present in the environment regardless of the cwd.

**Comment by webknjaz** [comment]
I want to highlight several things discovered using [remote_pdb](https://github.com/ionelmc/python-remote-pdb):
* altering `PYTHONPATH` and/or `PATH` or `sys.path` in runtime doesn't help
* `chdir()` to the cherrypy's package dir helps
* reproducible with `-m` 
* `import cherrypy` works
* neither of `from cherrypy import _cpwsgi_server` / `from . import _cpwsgi_server` work

Ideas:
* probably old python versions are trying to lookup import from `cherrypy.__init__`

**Comment by webknjaz** [comment]
TODO:
* [x] check `cherrypy.__path__` and `cherrpy.__file__`

**Comment by jaraco** [comment]
`cherrypy.__path__` is `['cherrypy']`
`cherrypy.__file__` is `'cherrypy/__init__.pyc'` (Python 2.7).

Now I know what's going on. I've seen this before. On Python prior to 3.4, when you import a package that's resolved from a `sys.path` entry of `''` or any relative path, the package gets a `__file__` that's relative. See [this answer](http://stackoverflow.com/a/7116925/70170) for some insight.

So now the question I have is - why is this effect only relevant with these recent changes? I do know that pytest does add the absolute path to the current directory during startup, but if that happens after 'cherrypy' has been imported, it may be too late.

My other question is, what is the purpose of that `chdir`? Is it cruft that we can just remove and thus forget about this issue?

**Comment by jaraco** [comment]
Looking at the blame history, it seems that `chdir` originated in 130818aa8b6 as part of a wholesale commit, so that doesn't provide any insight.

At this point, I'm leaning toward two possible options:

1. Just accept the PR as is, omitting that line until someone complains.
2. Add something to the test setup to replace the relative sys.path with an absolute one (Python 3.3 and earlier only).

**Comment by webknjaz** [comment]
3.3:
```
$ telnet 127.0.0.1 46207
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
> /cherrypy/_cpserver.py(167)httpserver_from_self()
(Pdb) import cherrypy
(Pdb) cherrypy.__file__
'./cherrypy/__init__.py'
(Pdb) cherrypy.__path__
['./cherrypy']
(Pdb) from cherrypy import _cpwsgi_server
*** ImportError: cannot import name _cpwsgi_server
(Pdb) from . import _cpwsgi_server
*** ImportError: cannot import name _cpwsgi_server
```

**Comment by webknjaz** [comment]
@jaraco there's a variable in that module called `_module__file__base`, we could alternatively `chdir()` there.

In fact while using daemon mode I've been facing an issue for a while: I couldn't use relative path to the app's configs because of chdir (but I never thought it's done explicitly, I was sure CWD is reset during double fork). Removing it obviously fixes this problem as well :)
