### ISSUE TITLE
socket.timeout: The write operation timed out

### ISSUE THREAD

**Issue by aniljava** [cherrypy/cherrypy#1575]
* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Several socket.timeout stack traces on error logs. No documentation to address this issue. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem**.

Lots of following trace in error logs.

    [10/Mar/2017:11:13:44] ENGINE socket.error 'The write operation timed out'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 960, in communicate
        req.respond()
      File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 786, in respond
        self.server.gateway(self).respond()
      File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 101, in respond
        self.write(chunk)
      File "/usr/local/lib/python3.5/dist-packages/cheroot/wsgi.py", line 183, in write
        self.req.write(chunk)
      File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 839, in write
        self.conn.wfile.write(chunk)
      File "/usr/local/lib/python3.5/dist-packages/cheroot/makefile.py", line 26, in write
        self._flush_unlocked()
      File "/usr/local/lib/python3.5/dist-packages/cheroot/makefile.py", line 35, in _flush_unlocked
        n = self.raw.write(bytes(self._write_buf))
      File "/usr/lib/python3.5/socket.py", line 593, in write
        return self._sock.send(b)
      File "/usr/lib/python3.5/ssl.py", line 861, in send
        return self._sslobj.write(data)
      File "/usr/lib/python3.5/ssl.py", line 586, in write
        return self._sslobj.write(data)
    socket.timeout: The write operation timed out

* **What is the expected behavior?**

If fatal or of concern, guide to address if not, ability to silence.

* **What is the motivation / use case for changing the behavior?**

Need a guide that google can pick up for any one else having similar issues.

* **Please tell us about your environment:**

- Python version: Python 3.5.2
- OS: Linux n2 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
This should probably be opened in cheroot repo

**Comment by webknjaz** [comment]
Closing in flavour of cherrypy/cheroot#20
