### ISSUE TITLE
Exception if client closes socket "ungracefully"

### ISSUE THREAD

**Issue by dfrison01** [cherrypy/cherrypy#1696]
[Possible bug report]
The mounted app receives a REST-styled POST, grabs a (large) file, then returns a simple string. Behavior can be reproduced both across multiple browsers and by python's "requests" module, just by closing the connection abruptly (client-side).

```
[2018-03-02 10:09:13,671] [ERROR] {_cplogging.py:222} - HTTP 
Traceback (most recent call last):
  File "D:\Python354\lib\site-packages\cherrypy\_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "D:\Python354\lib\site-packages\cherrypy\_cprequest.py", line 683, in _do_respond
    self.body.process()
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 986, in process
    super(RequestBody, self).process()
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 563, in process
    proc(self)
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 226, in process_multipart_form_data
    process_multipart(entity)
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 218, in process_multipart
    part.process()
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 561, in process
    self.default_proc()
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 721, in default_proc
    self.file = self.read_into_file()
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 736, in read_into_file
    self.read_lines_to_boundary(fp_out=fp_out)
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 673, in read_lines_to_boundary
    line = self.fp.readline(1 << 16)
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 857, in readline
    data = self.read(chunksize)
  File "D:\Python354\lib\site-packages\cherrypy\_cpreqbody.py", line 821, in read
    data = self.fp.read(chunksize)
  File "D:\Python354\lib\site-packages\cheroot\server.py", line 315, in read
    data = self.rfile.read(size)
  File "D:\Python354\lib\_pyio.py", line 1000, in read
    return self._read_unlocked(size)
  File "D:\Python354\lib\_pyio.py", line 1040, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "D:\Python354\lib\socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out


[2018-03-02 10:09:13,671] [WARNING] {_cplogging.py:222} - ENGINE socket.error 'cannot read from timed out object'
Traceback (most recent call last):
  File "D:\Python354\lib\site-packages\cheroot\server.py", line 1152, in communicate
    req.respond()
  File "D:\Python354\lib\site-packages\cheroot\server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "D:\Python354\lib\site-packages\cheroot\wsgi.py", line 136, in respond
    self.write(chunk)
  File "D:\Python354\lib\site-packages\cheroot\wsgi.py", line 215, in write
    self.req.send_headers()
  File "D:\Python354\lib\site-packages\cheroot\server.py", line 1083, in send_headers
    self.rfile.read(remaining)
  File "D:\Python354\lib\site-packages\cheroot\server.py", line 315, in read
    data = self.rfile.read(size)
  File "D:\Python354\lib\_pyio.py", line 1000, in read
    return self._read_unlocked(size)
  File "D:\Python354\lib\_pyio.py", line 1040, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "D:\Python354\lib\socket.py", line 573, in readinto
    raise OSError("cannot read from timed out object")
OSError: cannot read from timed out object
```

My config in case it's relevant:

```python
        serverConf = {'server.socket_port': port,
                       'server.socket_host': host,
                       'server.socket_timeout': 60,
                       'server.max_request_body_size' : 0,
                       'tools.secureheaders.on': True,
                       'engine.autoreload.on' : False,
                       }
```

Please note that there are two exceptions attached (generated and logged with the same timestamp), one as ERROR, the second one as WARN.

Is this really some sort of bug? How should I safely catch and silence those exceptions without further concern? Thanks in advance, and sorry for the poor "engrish" ;]

**Comment by webknjaz** [comment]
We might probably introduce a nicer logging for this. Obviously, reading from a dead socket woudn't work, but we should be fine w/o flooding logs w/ exceptions.
