### ISSUE TITLE
webtest module doesn't import

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1708]
It seems at some point the webtest module was broken:

```
~ $ rwt cherrypy
Collecting cherrypy
  Using cached https://files.pythonhosted.org/packages/b8/6d/d0d951dee5ba50900eccb71ef501a847d0392f50056d36234740f97a2ef8/CherryPy-14.2.0-py2.py3-none-any.whl
Collecting portend>=2.1.1 (from cherrypy)
  Using cached https://files.pythonhosted.org/packages/16/20/d98f22a2a5b1d7f5ab3a38154f7a1dd87846f2c5881f4b6929bdd1624e72/portend-2.2-py2.py3-none-any.whl
Collecting six>=1.11.0 (from cherrypy)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cheroot>=6.2.4 (from cherrypy)
  Using cached https://files.pythonhosted.org/packages/67/2d/2adc51ca551c1a404dadf49b60c9027d950967f4dc598804aba1ef30461e/cheroot-6.2.4-py2.py3-none-any.whl
Collecting tempora>=1.8 (from portend>=2.1.1->cherrypy)
  Using cached https://files.pythonhosted.org/packages/55/f4/6909c23d920192dc9d2bb0d0841abb561f58fb6c816cf593a35dda0a800c/tempora-1.11-py2.py3-none-any.whl
Collecting more-itertools>=2.6 (from cheroot>=6.2.4->cherrypy)
  Using cached https://files.pythonhosted.org/packages/7a/46/886917c6a4ce49dd3fff250c01c5abac5390d57992751384fe61befc4877/more_itertools-4.1.0-py3-none-any.whl
Collecting backports.functools-lru-cache (from cheroot>=6.2.4->cherrypy)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting pytz (from tempora>=1.8->portend>=2.1.1->cherrypy)
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Installing collected packages: pytz, six, tempora, portend, more-itertools, backports.functools-lru-cache, cheroot, cherrypy
Successfully installed backports.functools-lru-cache-1.5 cheroot-6.2.4 cherrypy-14.2.0 more-itertools-4.1.0 portend-2.2 pytz-2018.4 six-1.11.0 tempora-1.11
Python 3.7.0b4 (v3.7.0b4:eb96c37699, May  2 2018, 04:13:13)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cherrypy.test.webtest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-t9m6qa9j/cherrypy/test/webtest.py", line 4, in <module>
    from cheroot.test.webtest import (  # noqa
ImportError: cannot import name 'TerseTestResult' from 'cheroot.test.webtest' (/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-t9m6qa9j/cheroot/test/webtest.py)
```

**Comment by jaraco** [comment]
I see the note in the changelog for v12.0.1 indicating that this module was intended to be working.

**Comment by jaraco** [comment]
Looks like cherrypy/cheroot@6bfef14a is implicated.

**Comment by jaraco** [comment]
And also implicated in a619083b, which would have caught this error.

**Comment by webknjaz** [comment]
cherrypy/cheroot#82
