### ISSUE TITLE
global variable not defined in validate_password

### ISSUE THREAD

**Issue by ccsalway** [cherrypy/cherrypy#1733]
* **I'm submitting a ...**
- [ x ] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I don't think it's a bug but it's a strange behaviour.

* **What is the current behavior?**
I'm trying to use basic auth. I have the config as below. I have the validate_password in a separate file.  The config file contains the property ADADDRS.  When I try to run this, I get an error.

```
conf = {
    '/': {
        'tools.response_headers.on': True,
        'tools.response_headers.headers': [('Content-Type', 'text/plain;charset=utf-8')],
        'tools.auth_basic.on': True,
        'tools.auth_basic.realm': ADDOMAIN,
        'tools.auth_basic.checkpassword': validate_password,
    }
}
```

```
ADADDRS='ldaps://127.0.0.1'
```

```
from ad import AD
from config import *  <--- in here is ADADDRS

def validate_password(realm, username, password):
    return AD(ADADDRS, realm).connect(username, password)
```

```
[29/Aug/2018:15:51:03] HTTP 
Traceback (most recent call last):
  File "/var/www/api/venv/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/var/www/api/venv/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 686, in _do_respond
    self.hooks.run('before_handler')
  File "/var/www/api/venv/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 116, in run
    raise exc
NameError: global name 'ADADDRS' is not defined
```

- CherryPy version: 17.3.0
- Python version: 2.7.10

**Comment by webknjaz** [comment]
😱 This was fast

**Comment by ccsalway** [comment]
I had a round dependency :)  in my config i had require file1 and in file1 i had require config
