### ISSUE TITLE
File-based sessions on Windows, locking issues

### ISSUE THREAD

**Issue by pannal** [cherrypy/cherrypy#1750]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
This is the setup:
  * A CherryPy application that serves assets through a defined handler, which makes `requests.Request` requests to another HTTP server
  * Both the default handler and the assets handler make use of sessions
  * When the default handler is hit, there are intermediate requests to the assets handler from the browser, which might occur while the default handler is still active

When using `cherrypy.lib.sessions.FileSession` on a Windows environment, there seem to be issues in this particular setup.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
```python-traceback
[23/Oct/2018:15:34:36]
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cheroot\wsgi.py", line 147, in respond
    self.write(chunk)
  File "C:\Python35\lib\site-packages\cheroot\wsgi.py", line 228, in write
    self.req.write(chunk)
  File "C:\Python35\lib\site-packages\cheroot\server.py", line 1089, in write
    self.conn.wfile.write(chunk)
  File "C:\Python35\lib\site-packages\cheroot\makefile.py", line 31, in write
    self._flush_unlocked()
  File "C:\Python35\lib\site-packages\cheroot\makefile.py", line 40, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "C:\Python35\lib\socket.py", line 594, in write
    return self._sock.send(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cherrypy\_cptree.py", line 160, in release_serving
    req.close()
  File "C:\Python35\lib\site-packages\cherrypy\_cprequest.py", line 511, in close
    self.hooks.run('on_end_request')
  File "C:\Python35\lib\site-packages\cherrypy\_cprequest.py", line 114, in run
    raise exc
  File "C:\Python35\lib\site-packages\cherrypy\_cprequest.py", line 104, in run
    hook()
  File "C:\Python35\lib\site-packages\cherrypy\_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "C:\Python35\lib\site-packages\cherrypy\lib\sessions.py", line 716, in close
    sess.release_lock()
  File "C:\Python35\lib\site-packages\cherrypy\lib\sessions.py", line 570, in release_lock
    os.remove(self.lock._path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:\\data\\___small\\kitana\\data\\sessions\\session-a966d8ed383ad6b2f19e7934dd0a550af5d7ec1d.lock'
```

* **What is the expected behavior?**
It should work.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Cheroot version: X.X.X
- CherryPy version: 18.0.1
- Python version: 3.5.4
- OS: Windows 10 x64
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
This can be "fixed" by adding `PermissionError` to `FileSession.release_lock` - although I wouldn't exactly call this a suitable fix:
```diff
     def release_lock(self, path=None):
         """Release the lock on the currently-loaded session data."""
         self.lock.close()
-        with contextlib.suppress(FileNotFoundError):
+        with contextlib.suppress(FileNotFoundError, PermissionError):
             os.remove(self.lock._path)
         self.locked = False
```

**Comment by webknjaz** [comment]
I think we have concurrency problems with FileSession in general as demonstrated by test being unstable...

cc @jaraco
