### ISSUE TITLE
Google App Engine - ImportError: No module named grp 

### ISSUE THREAD

**Issue by zippy84** [cherrypy/cherrypy#1756]
I'm trying to run CherryPy in Googles App Engine. Because I only can use Python 2.7 I installed an older version of CherryPy with pip install -t /home/zippy/ecl/ecl_cherrypy/lib "CherryPy==17.4.0". 

And now I get:

```
Traceback (most recent call last):
  File "/home/zippy/ecl/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/home/zippy/ecl/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/home/zippy/ecl/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/home/zippy/ecl/ecl_cherrypy/ecl.py", line 9, in <module>
    import cherrypy
  File "/home/zippy/ecl/ecl_cherrypy/lib/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/home/zippy/ecl/ecl_cherrypy/lib/cherrypy/_cprequest.py", line 13, in <module>
    from cherrypy import _cpreqbody
  File "/home/zippy/ecl/ecl_cherrypy/lib/cherrypy/_cpreqbody.py", line 135, in <module>
    import cheroot.server
  File "/home/zippy/ecl/ecl_cherrypy/lib/cheroot/server.py", line 102, in <module>
    import grp
  File "/home/zippy/ecl/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py", line 1095, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named grp
```
Could you say what's wrong with it?

`python2 -c "import grp"` works fine.

**Comment by zippy84** [comment]
`sys.path` right before `import grp` is 

`/home/zippy/ecl/ecl_cherrypy;/home/zippy/ecl/ecl_cherrypy/lib;/home/zippy/ecl/google_appengine;/home/zippy/ecl/google_appengine;/usr/lib64/python2.7;/usr/lib64/python2.7/lib-dynload;/home/zippy/ecl/google_appengine/lib/jinja2-2.6;/home/zippy/ecl/google_appengine/lib/markupsafe-0.15;/home/zippy/ecl/google_appengine/lib/setuptools-0.6c11;/home/zippy/ecl/google_appengine/lib/protorpc-1.0;/home/zippy/ecl/google_appengine/lib/pytz-2017.3;/home/zippy/ecl/google_appengine/lib/webapp2-2.3;/home/zippy/ecl/google_appengine/lib/webob-1.1.1;/home/zippy/ecl/google_appengine/lib/werkzeug-0.11.10;/home/zippy/ecl/google_appengine/lib/yaml-3.10`

and grp is located here

```python
>>> import grp
>>> grp.__file__
'/usr/lib64/python2.7/lib-dynload/grp.so'
```

**Comment by zippy84** [comment]
Thanks for the answer. This is the reason for the ImportError:

> Libraries that maintain databases on disk are not enabled in Python for Google App Engine

It makes sense. CherryPy worked already with GAE, but I used an older version of CherryPy. The `import grp` must be something new.

GAE is free.

**Comment by webknjaz** [comment]
The update you're looking for is inside of Cheroot project, which implements HTTP and WSGI layer used by CherryPy. That's why I'm moving this issue over there.

It happens @ https://github.com/cherrypy/cheroot/blame/b0a7d7a/cheroot/server.py#L102

This is about the feature retrieving info about the process connected over plain old UNIX socket. Basically, it figures out "who's on the other side of the wire", PID, UID and GID, and then depending on the toggle also tries to resolve those IDs into meaningful names. That's what these imports are for.
It was introduced in Cheroot v6.2.0 (https://cheroot.cherrypy.org/en/latest/history.html#v6-2-0) with matching adapter added in CherryPy v14.1.0 (https://docs.cherrypy.org/en/latest/history.html#v14-1-0).

I think, as a workaround, pinning `Cheroot<6.2.0` should temporarily fix the issue for you until it's fixed in upstream.
