### ISSUE TITLE
socket_timeout breaks http1.1 connection reuse

### ISSUE THREAD

**Issue by johnkrugger** [cherrypy/cherrypy#1780]
**I'm submitting a ...**
- [ ] bug report

**What is the current behavior?**
Setting server.socket_timeout to 0 will prevent http/1.1 connection reuse. Connections will be killed with RST by cherrypy. Which was high unexpected as I don't even get a warning about it in the logs. Only after looking at the traffic in wireshark did I understand that was happening between two applications. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

Really simple app:
```
import cherrypy

class Example(object):
    @cherrypy.expose
    def index(self):
        return 'Test'

if __name__ == '__main__'
    cherrypy.config.update(
        {
            'server.socket_host': '0.0.0.0',
            'server.socket_port': 8666,
            'server.socket_timeout': 0,
            'environment': 'production',
            'log.screen': True
        }
    )

    cherrypy.quickstart(Example())
```
Testing with curl:
curl -v http:/localhost:8666/ http:/localhost:8666/ http:/localhost:8666/

Will result in:
* Recv failure: Connection reset by peer
* Connection died, retrying a fresh connect

**What is the expected behavior?**
I expected cherrypy to be able to handle HTTP/1.1 connection reuse when trying to use non-blocking sockets just as it does when using blocking sockets. This actually resulted in other applications not being able to communicate with cherrypy because they don't retry as curl does.

**What is the motivation / use case for changing the behavior?**
Improve HTTP/1.1 support

**Please tell us about your environment:**

- CherryPy version: 8.9.1-2 Ubuntu package
- Python version: 3.6.7
- OS: Ubuntu 18.04 LTS 

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by webknjaz** [comment]
@johnkrugger that version is quite old. Have you tried the latest one? The low-level networking code is now under https://github.com/cherrypy/cheroot

**Comment by johnkrugger** [comment]
I understand it is an older version, however it is what is being packaged by Ubuntu 18.04 LTS and it is what they are keeping for 19.04 and later version. 

Created a new virtual machine and installed version 18.1.1 through pip3. Still have the same problem and a traceback to go with it:
```

Traceback (most recent call last):
  File "/home/tester/.local/lib/python3.6/site-packages/cheroot/server.py", line 1263, in communicate
    req.parse_request()
  File "/home/tester/.local/lib/python3.6/site-packages/cheroot/server.py", line 719, in parse_request
    success = self.read_request_line()
  File "/home/tester/.local/lib/python3.6/site-packages/cheroot/server.py", line 760, in read_request_line
    request_line = self.rfile.readline()
  File "/home/tester/.local/lib/python3.6/site-packages/cheroot/server.py", line 302, in readline
    data = self.rfile.readline(256)
  File "/usr/lib/python3.6/_pyio.py", line 511, in readline
    b = self.read(nreadahead())
  File "/home/tester/.local/lib/python3.6/site-packages/cheroot/makefile.py", line 411, in read
    self.bytes_read += len(val)
TypeError: object of type 'NoneType' has no len()
```

Should I open a new bug on the cheroot project for version 18.1.1? 
Are you still supporting these older versions of cherrypy? If not, I have to go and open a ticket for Ubuntu too.

**Comment by webknjaz** [comment]
No, we're not backporting anything. Occasional backports only go to 17.x branch. But that doesn't have what's in Cheroot and Cheroot doesn't have any backporting set up. Try its master branch to confirm whether it still behaves the same. It there's a bug, create an issue there and if possible add a Cheroot-specific reproducer to isolate the conditions and make it easier to track it down.

Meanwhile, there's a refactoring PR which may affect this so be sure to test that too: https://github.com/cherrypy/cheroot/pull/199.

P.S. You don't need a full VM for testing, just use a virtualenv.

**Comment by johnkrugger** [comment]
Was having a look at the code near the error and the problem is that read is returning None, which the code doesn't expect. And actually it shouldn't expect it because the documentation for BufferedIOBase states:

> In addition, those methods can raise BlockingIOError if the underlying raw stream is in non-blocking mode and cannot take or give enough data; unlike their RawIOBase counterparts, they will never return None.

Ref: https://docs.python.org/3/library/io.html#io.BufferedIOBase

Opening /usr/lib/python3.6/_pyio.py shows me that the read function can actually return None and no BlockingIOError are raise.

We even have an open python bug about it:
https://bugs.python.org/issue13322
https://bugs.python.org/issue35869

It seems turning on non-blocking sockets will get you into trouble as the code will not work as outlined in the documentation.

**Comment by webknjaz** [comment]
Still, let's document this under Cheroot.
