### ISSUE TITLE
Re-spawning fails if cherrypy started from IDLE (commandline do)

### ISSUE THREAD

**Issue by iconberg** [cherrypy/cherrypy#1788]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
BUG: Re-spawning fails if cherrypy detects an change on an imported module

**What is the current behavior?**
If an imported module is changed and the server is started from IDLE this happen:

```console
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: C:\Users\Administrator\Desktop\crashtest.py ============
[14/Jun/2019:13:34:01] ENGINE Listening for SIGTERM.
[14/Jun/2019:13:34:01] ENGINE Bus STARTING

Warning (from warnings module):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cpchecker.py", line 105
    warnings.warn(msg)
UserWarning: The Application mounted at '' has an empty config.
[14/Jun/2019:13:34:01] ENGINE Set handler for console events.
[14/Jun/2019:13:34:01] ENGINE Started monitor thread 'Autoreloader'.
[14/Jun/2019:13:34:01] ENGINE Serving on http://127.0.0.1:8080
[14/Jun/2019:13:34:01] ENGINE Bus STARTED
[14/Jun/2019:13:34:12] ENGINE Restarting because C:\Users\Administrator\Desktop\changelib.py changed.
[14/Jun/2019:13:34:12] ENGINE Stopped thread 'Autoreloader'.
[14/Jun/2019:13:34:12] ENGINE Bus STOPPING
[14/Jun/2019:13:34:12] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[14/Jun/2019:13:34:12] ENGINE Removed handler for console events.
[14/Jun/2019:13:34:12] ENGINE Bus STOPPED
[14/Jun/2019:13:34:12] ENGINE Bus EXITING
[14/Jun/2019:13:34:12] ENGINE Waiting for child threads to terminate...
[14/Jun/2019:13:34:12] ENGINE Bus EXITED
[14/Jun/2019:13:34:12] ENGINE Re-spawning C:\Program Files (x86)\Python37-32\pythonw.exe C:\Users\Administrator\Desktop\crashtest.py

=============================== RESTART: Shell ===============================
>>> 
```

Restarting from IDLE shows this:
```

============ RESTART: C:\Users\Administrator\Desktop\crashtest.py ============
[14/Jun/2019:13:34:22] ENGINE Listening for SIGTERM.
[14/Jun/2019:13:34:23] ENGINE Bus STARTING

Warning (from warnings module):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cpchecker.py", line 105
    warnings.warn(msg)
UserWarning: The Application mounted at '' has an empty config.
[14/Jun/2019:13:34:23] ENGINE Set handler for console events.
[14/Jun/2019:13:34:23] ENGINE Started monitor thread 'Autoreloader'.
[14/Jun/2019:13:34:24] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x02A11AF0>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\process\wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cpserver.py", line 180, in start
    super(Server, self).start()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\process\servers.py", line 177, in start
    portend.free(*self.bind_addr, timeout=Timeouts.free)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\portend.py", line 123, in free
    raise Timeout("Port {port} not free on {host}.".format(**locals()))
portend.Timeout: Port 8080 not free on 127.0.0.1.

[14/Jun/2019:13:34:24] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\process\wspbus.py", line 268, in start
    self.publish('start')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\process\wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: Timeout('Port 8080 not free on 127.0.0.1.')

[14/Jun/2019:13:34:24] ENGINE Bus STOPPING
[14/Jun/2019:13:34:24] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) already shut down
[14/Jun/2019:13:34:24] ENGINE Stopped thread 'Autoreloader'.
[14/Jun/2019:13:34:24] ENGINE Removed handler for console events.
[14/Jun/2019:13:34:24] ENGINE Bus STOPPED
[14/Jun/2019:13:34:24] ENGINE Bus EXITING
[14/Jun/2019:13:34:24] ENGINE Bus EXITED

=============================== RESTART: Shell ===============================
>>> 
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
Code:
[crashtest.zip](https://github.com/cherrypy/cherrypy/files/3290479/crashtest.zip)

Reprocdule with:

- Open crashtest.py from IDLE and run with F5
- Change a line in changelib.py and save
- Re-spawn fails

**What is the expected behavior?**
Re-spawn should work if cherrypy is started from IDLE, shell does.

**What is the motivation / use case for changing the behavior?**
shell and IDE should give the same results, 

**Please tell us about your environment:**

- Cheroot version: 6.5.5
- CherryPy version: 18.1.1
- Python version: 3.7.3
- OS: Win 2012 R2
- Browser: Firefox 67| IE 11

That problem does not seem to exists on linux.

**Comment by webknjaz** [comment]
I believe it's another caveat of Windows. It's quite hard to identify what the command line args were in such env. There's nothing we can do about it. It's probably one of the corner cases. Honestly, I think you're the first person in 10 years that I see using IDLE for development. Everybody else seems to use a proper terminal emulator :)

P.S. Plz don't upload archives, nobody downloads that. Just include a reproducer into the issue as a proper code block.

**Comment by webknjaz** [comment]
But if you figure it out, feel free to send a PR :) None of the Core Devs uses/has access to Windows env.

**Comment by iconberg** [comment]
Tried pycharm, it seems to work until i put a print or pprint for debugging issues in the code.
Than the code is restarted if i change a imported module,  but it goes on an error.
Could this a timing problem, if cherrypy.session is not ready fast enough?

```python-traceback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:/Users/Administrator/Documents/GitHub/pylabelserver/pylabelserver/webinterface.py", line 21, in index
    print('session id: ', cherrypy.session.id)
OSError: [Errno 22] Invalid argument
```

**Comment by webknjaz** [comment]
I'm not sure it's related to the reload. Autoreloader kinda replaces the process. But I don't know how this works on Windows as it doesn't have `exec` syscall.

I would assume that the stdout stream is still bound to the old process or smth like this. But I don't have a windows machine to debug this issue.

Would you be able to write a test which would demonstrate the problem in AppVeyor?

**Comment by iconberg** [comment]
I tried pycharm as IDE, the same problem occurs. It cannot restart and leaves a zombie python task not connected to the IDE anymore.

Maybe another expierenced user can see the cause, here is my code to reproduce this behavior,
start the crashtest.py from IDE and change the changelib.py (add or delete a pass), the autoreloader fails leaving a zombie task.



crashtest.py:
```python
import cherrypy
import changelib

class HelloWorld(object):
    @cherrypy.expose
    def index(self):
        return "Hello World!"

cherrypy.quickstart(HelloWorld())
```

changelib.py:
```python
def foo():
    pass
    pass
```

If anyone have an hint how to get the autoreload running i would get me to ease the development. 
Any hints welcome.

added: 
When i run my code (with engine.autoreload.on enabled) from shell i got the same problem too, maybe i have some minor mistake i cannot get, here is my project: [https://github.com/iconberg/pylabelserver](https://github.com/iconberg/pylabelserver)
Still prototyping.

webinterface.py:

```python
import os
import cherrypy
import jinja2
import json
import importlib

from pylabelserver import helper

import pprint


class WebLabelInterface(object):


    def __init__(self):
        helper.open_browser('http://localhost:8080')


    @cherrypy.expose
    def index(self, *args, **kwargs):
        #print('session id: ', cherrypy.session.id)
        cherrypy.session['my_id'] = cherrypy.session.id
        #pprint.pprint(kwargs)

        d = {}
        d['my_id'] = cherrypy.session['my_id']
        d['print_data'] = {}
        d['search_for'] = kwargs.get('search_for', '')
        d['printer_list'] = helper.printer_list()

        if kwargs.get('form_button', None) == 'search' and d['search_for']:
            for ig in helper.input_generator_list():
                input_generator = importlib.import_module('input_generator.{}'.format(os.path.splitext(ig)[0]))
                para_list = [d['search_for']]
                label_file = input_generator.create_label_data(para_list, sessionid=d['my_id'])
                if label_file:
                    with open(label_file, mode='r') as f:
                        d['print_data'] = json.load(f)
                        cherrypy.session['print_data'] = d['print_data']
                    break
                else:
                    cherrypy.session['print_data'] = {}
        else:
            d['print_data'] = cherrypy.session.get('print_data', None)

        if kwargs.get('form_button', None) == 'print':
            if isinstance(kwargs.get('print', None), list):
                print_rows = [int(x) for x in kwargs.get('print', None)]
            else:
                print_rows = [int(kwargs.get('print', -1))]
            for k, e in d['print_data'].items():
                if int(k) in print_rows:
                    e['print_row'] = True
                else:
                    e['print_row'] = False
        
        template = env.get_template('main.html')
        html = template.render(d)
        return html


if __name__ == '__main__':
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(helper.get_folder('templates')),
        trim_blocks = True,
        lstrip_blocks = True,
        )
    
    config = {
        'tools.sessions.on': True,
        'tools.staticdir.on': True,
        'tools.staticdir.dir': helper.get_folder('static'),
        #'engine.autoreload.on': False, # Remove if issue https://github.com/cherrypy/cherrypy/issues/1545 is sloved
        }
    appconfig = {}
    cherrypy.config.update(config)    
    cherrypy.quickstart(WebLabelInterface(), '/', {'/': appconfig})
```

**Comment by iconberg** [comment]
> 
> 
> I'm not sure it's related to the reload. Autoreloader kinda replaces the process. But I don't know how this works on Windows as it doesn't have `exec` syscall.
> 
> I would assume that the stdout stream is still bound to the old process or smth like this. But I don't have a windows machine to debug this issue.
> 
> Would you be able to write a test which would demonstrate the problem in AppVeyor?

Sorry, was on holidy and didnt see that message on my leaved open browser on my remote machine for it.
I dont know AppVeyor, i take a look at it.

added:
I cannot install an appveyor server here. You need an running windows system with the running project on it to examine the problem, right?
Let me some time, i guess i can organize and install an win somewhere in a cloud.

**Comment by webknjaz** [comment]
You don't need to install the CI itself. We already have it integrated. You just need to add tests.

**Comment by webknjaz** [comment]
The second reproducer you posted seems different. Is it the same problem?

**Comment by brainbytes42** [comment]
Hello,

I came across the same problem and found this issue. 

> I'm not sure it's related to the reload. Autoreloader kinda replaces the process. But I don't know how this works on Windows as it doesn't have `exec` syscall.
> 
> I would assume that the stdout stream is still bound to the old process or smth like this. But I don't have a windows machine to debug this issue.

My Environment is Windows + IntelliJ with Python-Plugin (which hould by quite equal to PyCharm in effect).

Although I wouldn't know how to write a proper test for that, maybe the following observations may help - either to fix or at least circumvent this issue.

After the Autoreloader has re-spawned the server (because of changes to the python-file), the process ID (PID) has changed, so the cited assumption above seems to be correct.

In Windows, you can get the PID like so (see [here](https://stackoverflow.com/a/39633428/6748496)): `netstat -ano | findstr 127.0.0.1:8080`

If you check the PID before and after a change to the file and the respective re-spawning, the PID is not the same. And probably, the IntelliJ-output just stays with the old PID... :-(

To circumvent this issue, you can use the windows console or, if you want to stay in IntelliJ, the Terminal, which is basically the same. To streamline this a little bit, you can define a new Shell-Script-Runconfiguration with script text `python yourServerScript.py`.
