### ISSUE TITLE
Utilising Cython with CherryPy

### ISSUE THREAD

**Issue by aytey** [cherrypy/cherrypy#1814]
**I'm submitting a ...**
- [X] bug report
- [X] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

This is probably a feature request, but it could also be classed a bug in the current implementation.

**What is the current behavior?**

If you use Cython to convert certain Python code into executable machine code (e.g., a `.so` on Linux or a `.pyd` on Windows), then CherryPy's ability to detect that the method has been `expose`'d does not seem to work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

Some example code would look like this:

```python
import cherrypy

class Router(object):
    config = {}

    @cherrypy.expose
    def index(self):
        return "hello world"

def start_server():
    cherrypy.config.update({
        'server.socket_host': '127.0.0.1',
        'server.socket_port': 8127
    })

    cherrypy.tree.mount(Router(), '/route', Router.config)
    cherrypy.engine.start()
    cherrypy.engine.block()

# Run, then navigate to 127.0.0.1:8127/route in a browser
def main():
    start_server()
```

You can then write a simple "wrapper" just to call into the above:

```python
from test import main

if __name__ == "__main__":
    main()

# EOF
```

If this code is run as "normal" Python and you request `127.0.0.1:8127/route`, then you get the expected "hello world".

However, if you Cythonize this module (`cythonize -a -i test.pyx`) then you obtain the following response:

```python-traceback
        <h2>404 Not Found</h2>
        <p>The path '/route/' was not found.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/tmp/cython/cherrypy/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/tmp/cython/cherrypy/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/tmp/cython/cherrypy/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/tmp/cython/cherrypy/cherrypy/_cperror.py", line 416, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/route/' was not found.")
</pre>
```

**What is the expected behavior?**

I would have expected things to "just work", even if the code had been Cythonised. I do not think that this is a Cython problem.

Considering code that is/isn't Cythonised, we have the following:

```python
print(isinstance(cython_func, types.FunctionType))          # False
print(isinstance(cython_func, types.LambdaType))            # False
print(isinstance(cython_func, types.BuiltinFunctionType))   # True
print(isinstance(cython_func, types.BuiltinMethodType))     # True

print(isinstance(normal_func, types.FunctionType))          # True
print(isinstance(normal_func, types.LambdaType))            # True
print(isinstance(normal_func, types.BuiltinFunctionType))   # False
print(isinstance(normal_func, types.BuiltinMethodType))     # False
```

If you search for this online, there are number of places where this has existed previously:

- https://trac.sagemath.org/ticket/16309
- https://cython-devel.python.narkive.com/hKR75bIJ/should-we-monkey-patch-inspect-isfunction

In particular, this response: https://trac.sagemath.org/ticket/16309#comment:2

Given that this issue (inside of CherryPy) is related to how CherryPy detects if something is a method or not, I changed this line:

- https://github.com/cherrypy/cherrypy/blob/master/cherrypy/_helper.py#L28

from:

```python
if isinstance(func, decoratable_types):
```

to be:

```python
if isinstance(func, decoratable_types) or hasattr(func, 'func_code'):
```

and now the Cythonated version works!

**What is the motivation / use case for changing the behavior?**

We have some code that it we have optimised to work with Cython, and our plan was to endeavour to Cythonize as-much-as-possible, to avoid having a mix of binary and non-binary code.

Plus, more generally, I think that this is an issue that CherryPy does not support Cythonated code.

**Please tell us about your environment:**

- Cheroot version: *latest git checkout* c7ca7ff
- CherryPy version: *latest git checkout* 7369728
- Cython version: 0.29.13
- Python version: 3.6.3
- OS: "CentOS Linux release 7.6.1810 (Core)" (kernel: 3.10.0-957.27.2.el7.x86_64)
- Browser: all

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

I am not sure if it is a suggested fix, but if the the `hasattr(func, 'func_code')` check is appropriate to the project, then I am more than happy to open up a PR for this.

**Comment by webknjaz** [comment]
@andrewvaughanj thanks for the issue!

I'll mark it as a feature request as this is not something that we're testing against or promise to work.

I'm open to accepting a PR, given that it also supplies corresponding tests that would prevent future regressions.

What are the return values of `type(cython_func)` and `type(normal_func)`? Also, can we just extend `decoratable_types` variable to also list `types.BuiltinFunctionType`/`types.BuiltinMethodType` instead of doing that attribute lookup?

**Comment by aytey** [comment]
Hi @webknjaz,

Thanks for taking a look!

If I wanted to add some tests for this, do you know how these would look? Is it reasonable that CherryPy's test-suite could be setup such that Cython is accessible? Can you provide any pointers?

I completely agree that a contribution without tests is worthless.

Cheers,

Andrew

**Comment by webknjaz** [comment]
I mean, I'd probably accept a contribution w/o tests but then it'd be fragile which would make me unhappy :)

As for tests, I'm not sure. You'd probably have to set up something custom. Maybe a file/folder (`.py`) under tests with a simple server and a fixture for pytest that'd cytonize it into a corresponding binary and emit two module variants that you'd import/run in the test func.
