### ISSUE TITLE
Long (~30s) action generates timeout error

### ISSUE THREAD

**Issue by 12gabriel3** [cherrypy/cherrypy#1854]
I can run any action as long as they are quick actions, but if the action takes a couple of seconds, there is a timeout error. Here are the logs. The logs are mixed up because `rasa run --log-file actions.log actions` is not working for me.

```
2020-04-30 04:47:40 2020-04-30 04:47:40 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_TEDPolicy

2020-04-30 04:47:40 2020-04-30 04:47:40 DEBUG    rasa.core.processor  - Predicted next action 'action_get_sales' with confidence 0.94.

2020-04-30 04:47:40 2020-04-30 04:47:40 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_get_sales'.

2020-04-30 04:47:41 2020-04-30 04:47:41 WARNING  rasa.core.channels.slack  - Received message on unsupported channel: C012046DL5P

2020-04-30 04:47:41 Exception occurred while handling uri: 'http://localhost:5055/webhook'#012Traceback (most recent call last):#012  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn#012    (self._dns_host, self.port), self.timeout, **extra_kw)#012  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection#012    raise err#012  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection#012    sock.connect(sa)#012ConnectionRefusedError: [Errno 111] Connection refused#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen#012    chunked=chunked)#012  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request#012    conn.request(method, url, **httplib_request_kw)#012  File "/usr/lib/python3.7/http/clien

2020-04-30 04:47:41 2020-04-30 04:47:41 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_get_sales'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.

2020-04-30 04:47:41 2020-04-30 04:47:41 DEBUG    rasa.core.processor  - Failed to execute custom action.#012Traceback (most recent call last):#012  File "/home/12gabriel3/.local/lib/python3.7/site-packages/rasa/core/actions/action.py", line 549, in run#012    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT#012  File "/home/12gabriel3/.local/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 150, in request#012    response.status, response.reason, await response.content.read()#012rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'\n    <h1>Internal Server Error</h1>\n    <p>\n        The server encountered an internal error and cannot complete\n        your request.\n    </p>\n''#012#012The above exception was the direct cause of the following exception:#012#012Traceback (most recent call last):#012  File "/home/12gabriel3/.local/lib/python3.7/site-packages/rasa/core/processor.py", line 644, in _run_action#012    events = await action.ru

2020-04-30 04:47:41 2020-04-30 04:47:41 DEBUG    rasa.core.processor  - Action 'action_get_sales' ended with events '[]'.
````

Feel free to ask any details and to recommend other tests

**Comment by 12gabriel3** [comment]
Sorry, wrong repo
