### ISSUE TITLE
SSL Cipher Missing, Decryption Failed Bad Record Mac Exceptions

### ISSUE THREAD

**Issue by Kaleemulla** [cherrypy/cherrypy#1870]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
Report bug

**What is the current behavior?**
Cherrypy engine throws following exceptions and suddenly crashes 
```python-traceback
[03/Sep/2020:05:38:56] ENGINE Bus STARTED
[03/Sep/2020:05:54:25] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1776, in serve
    self.tick()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1999, in tick
    conn = self.connections.get_conn(self.socket)
  File "/usr/local/lib/python3.6/site-packages/cheroot/connections.py", line 180, in get_conn
    return self._from_server_socket(server_socket)
  File "/usr/local/lib/python3.6/site-packages/cheroot/connections.py", line 199, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.6/site-packages/cheroot/ssl/builtin.py", line 244, in wrap
    sock, do_handshake_on_connect=True, server_side=True,
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: REQUIRED_CIPHER_MISSING] required cipher missing (_ssl.c:877)

[03/Sep/2020:05:55:25] ENGINE socket.error 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1259, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 700, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 741, in read_request_line
    request_line = self.rfile.readline()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 298, in readline
    data = self.rfile.readline(256)
  File "/usr/lib64/python3.6/_pyio.py", line 511, in readline
    b = self.read(nreadahead())
  File "/usr/lib64/python3.6/_pyio.py", line 495, in nreadahead
    readahead = self.peek(1)
  File "/usr/lib64/python3.6/_pyio.py", line 1063, in peek
    return self._peek_unlocked(size)
  File "/usr/lib64/python3.6/_pyio.py", line 1070, in _peek_unlocked
    current = self.raw.read(to_read)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.6/ssl.py", line 968, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 830, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.6/ssl.py", line 587, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2334)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

i am using below web config
```python
CIPEHRS = ('ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+HIGH:DH+HIGH:RSA+AESGCM:RSA+AES:RSA+HIGH:!aNULL:!eNULL:!MD5:!DSS:!RC4:!DES:!3DES:!BF:!BF+CFB:!BF+ECB:!BF+OFB:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_DHE_RSA_WITH_AES_128_GCM_SHA256:TLS_DHE_DSS_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_SHA256:TLS_ECDHE_RSA_WITH_AES_128_SHA:TLS_ECDHE_ECDSA_WITH_AES_128_SHA:TLS_ECDHE_RSA_WITH_AES_256_SHA384:TLS_ECDHE_ECDSA_WITH_AES_256_SHA384:TLS_ECDHE_RSA_WITH_AES_256_SHA:TLS_ECDHE_ECDSA_WITH_AES_256_SHA:TLS_DHE_RSA_WITH_AES_128_SHA256:TLS_DHE_RSA_WITH_AES_128_SHA:TLS_DHE_DSS_WITH_AES_128_SHA256:TLS_DHE_RSA_WITH_AES_256_SHA256:TLS_DHE_DSS_WITH_AES_256_SHA:TLS_DHE_RSA_WITH_AES_256_SHA')

        web_config = {
            'global': {
                'server.environment': 'production',
                'server.socket_host': 10.10.1.1,
                'server.socket_port': 8050,
                'server.ssl_module': 'builtin',
                'server.ssl_certificate': '<path>',
                'server.ssl_private_key': '<path>',
                'server.ssl_ciphers': CIPHERS,
                'engine.autoreload.on': False
            },
            '/': {
                'tools.auth_basic.on': True,
                'tools.auth_basic.realm': 'web',
                'tools.auth_basic.checkpassword': validate_password,
                'tools.auth_basic.accept_charset': 'UTF-8',
            }
        }

        cherrypy.config.update({'engine.autoreload.on': False})
        cherrypy.engine.signals.subscribe()

        cherrypy.quickstart(myclass(), config=web_config)
```

**What is the expected behavior?**

To see the application running with crashing 

**What is the motivation / use case for changing the behavior?**

the application should work seamlessly

**Please tell us about your environment:**

- Cheroot version: 8.3.0
- CherryPy version: 18.5.0
- Python version: 3.6.8
- OS: Linux 3.10.0-1062.4.1.el7.x86_64
- Browser: Chrome

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

Maybe this is related to issue https://github.com/cherrypy/cheroot/issues/292 in cheroot but the errors i see are different. Let me know for any more info..

**Comment by Kaleemulla** [comment]
I see below too:
```python-traceback
08/Oct/2020:08:08:58] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1776, in serve
    self.tick()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1999, in tick
    conn = self.connections.get_conn(self.socket)
  File "/usr/local/lib/python3.6/site-packages/cheroot/connections.py", line 180, in get_conn
    return self._from_server_socket(server_socket)
  File "/usr/local/lib/python3.6/site-packages/cheroot/connections.py", line 199, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.6/site-packages/cheroot/ssl/builtin.py", line 244, in wrap
    sock, do_handshake_on_connect=True, server_side=True,
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: REQUIRED_CIPHER_MISSING] required cipher missing (_ssl.c:877)
```

**Comment by webknjaz** [comment]
1) It's not a crash but a traceback recorded in a log, same as https://github.com/cherrypy/cheroot/issues/292
2) The second traceback in the initial post looks like bad network connectivity happening around the time the request's been made. So the solution would be to fix your network.
3) The first traceback and the traceback in the second comment mean exactly what they say: the cipher mismatch happened. TLS client and server attempt to agree on a subset of common ciphers that both parties support during the handshake. If there's no common ciphers, they cannot proceed. You may need to find that specific client, see how it's set up, and decide if you want to support that or alternatively upgrade the TLS lib (or its setup) in that client.
