### ISSUE TITLE
`StaticTest.test_755_vhost` fails on armv7

### ISSUE THREAD

**Issue by a16bitsysop** [cherrypy/cherrypy#1896]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Building a package for several arch's armv7 fails a test all the others pass on

```python-traceback
__________________________ StaticTest.test_755_vhost ___________________________
6216self = <cherrypy.test.test_static.StaticTest testMethod=test_755_vhost>
6217    def test_755_vhost(self):
6218        self.getPage('/test/', [('Host', 'virt.net')])
6219        self.assertStatus(200)
6220        self.getPage('/test', [('Host', 'virt.net')])
6221>       self.assertStatus(301)
6222self       = <cherrypy.test.test_static.StaticTest testMethod=test_755_vhost>
6223cherrypy/test/test_static.py:303: 
6224_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
6225/usr/lib/python3.8/site-packages/cheroot/test/webtest.py:327: in assertStatus
6226    self._handlewebError(msg)
6227/usr/lib/python3.8/site-packages/cheroot/test/webtest.py:269: in _handlewebError
6228    i = getchar().upper()
6229/usr/lib/python3.8/site-packages/cheroot/test/webtest.py:76: in getchar
6230    fd = sys.stdin.fileno()
6231_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
6232self = <_pytest.capture.DontReadFromInput object at 0xf69df808>
6233    def fileno(self):
6234>       raise UnsupportedOperation("redirected stdin is pseudofile, has no fileno()")
6235E       io.UnsupportedOperation: redirected stdin is pseudofile, has no fileno()
6236self       = <_pytest.capture.DontReadFromInput object at 0xf69df808>
6237/home/buildozer/.local/lib/python3.8/site-packages/_pytest/capture.py:711: UnsupportedOperation
```
Full Build log:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/292025/raw

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

Logs above

**What is the expected behavior?**

The tests pass on all arches, this is same type of failure on all arch's if pytest v6 is used.

**What is the motivation / use case for changing the behavior?**

To get the build to pass for alpine linux

**Please tell us about your environment:**

- Cheroot version: 8.5.1
- CherryPy version: 18.6.0
- Python version: 3.8.7
- OS: alpine:edge
- Browser: NA

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)
Link above to armv7
x86_64 passing build here: https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/292020/raw

**Comment by webknjaz** [comment]
You didn't post the important bit:
```console
----------------------------- Captured stdout call -----------------------------

    ERROR: Status 408 Request Timeout does not match 301
    Show: [B]ody [H]eaders [S]tatus [U]RL; [I]gnore, [R]aise, or sys.e[X]it >> 
```

This suggests that the test expects 301 but this env seems to be so slow that it returns 408.

The response seems to be coming from https://github.com/cherrypy/cheroot/blob/9432fae8e4ffa56ac6daf4f56e4c66d25763c1ae/cheroot/server.py#L1300.

@a16bitsysop do you have a docker image that could be spawned on an RPi4? We need a reproducer to have anything actionable wrt issue. Or maybe you could attempt debugging it yourself.

FWIW maybe increasing the values of `server.socket_timeout` / `server.accepted_queue_timeout` in the test server would fix this. Needs testing tho.

**Comment by a16bitsysop** [comment]
Okay, sorry thought I had posted all the captured log part.  Yes I do have an RPi4 actually, will try on that with a docker image and try those values as well.

Also are you planning to update CherryPy tests to run on pytest6.x, I see there there are some merge requests for Cheroot relating to pytest, but couldn't see any for CherryPy.

**Comment by webknjaz** [comment]
Probably someday but we don't have much maintenance capacity to dive into it. It'd be easier if somebody contributed that. Also, I'd like to get rid of `unittest.TestCase` but that requires a lot of commitment.

**Comment by a16bitsysop** [comment]
I tried to do a reproducer here without alpine build environment as a few dependencies not added to alpine either yet:
https://github.com/a16bitsysop/CherryPy_test

It seems to just end the test instead of failing StaticTest, same on aarch64 which it should pass on?

**Comment by webknjaz** [comment]
> It seems to just end the test instead of failing StaticTest, same on aarch64 which it should pass on?

Sounds like it hits an interactive handler that requires a TTY and the env where you run your docker container doesn't allocate one.

**Comment by a16bitsysop** [comment]
I still can't get it working in docker, even tox has an invocation error at same point when starting a shell inside container to run tests.

So I started trying to fix tests for pytest6, I have pushed first 2 fixes but am stuck on the third failure. 

It is from this code in _cpwsgi.py

```python
    def close(self):                                                    
        """Close and de-reference the current request and response. (Core)"""
        streaming = _cherrypy.serving.response.stream                        
        self.cpapp.release_serving() 
``` 

Which gives the error:

```python-traceback
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
E               
E               Traceback (most recent call last):
E                 File "/root/b/cherrypy/_cpwsgi.py", line 282, in close
E                   self.cpapp.release_serving()
E               ResourceWarning: unclosed file <_io.BufferedRandom name=19>

cm         = <_pytest.unraisableexception.catch_unraisable_exception object at 0xf6440aa8>
err_msg    = 'Exception ignored in'
msg        = 'Exception ignored in: <_io.FileIO [closed]>\n\nTraceback (most recent call last):\n  File "/root/b/cherrypy/_cpwsgi.py", line 282, in close\n    self.cpapp.release_serving()\nResourceWarning: unclosed file <_io.BufferedRandom name=19>\n'

/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
```

I have tried clearing cache before `self.cpapp.release_serving()` but it just hangs, how can I get cherrypy to close the open files?

**Comment by webknjaz** [comment]
> I still can't get it working in docker, even tox has an invocation error at same point when starting a shell inside container to run tests.

Did you make sure to add `-it` to your commands?

> I have tried clearing cache before `self.cpapp.release_serving()` but it just hangs, how can I get cherrypy to close the open files?

For that, you'd need to do some debugging. From the log you posted it's completely unobvious what file descriptor it's talking about. Try at least learning that. Looking at the source, I think `release_serving()` publishes to `after_request` and I guess the expectation is that the subscribers would clean up their resources on this hook. But again, your log doesn't even mention the test name so I have no clue what's happening there.

**Comment by a16bitsysop** [comment]
Yes I used -it to start a shell inside the alpine docker, the test command is (calling them individually to debug):
 `pytest cherrypy/test/test_config_server.py  --tb=long`

And test failure is:
`FAILED cherrypy/test/test_config_server.py::ServerConfigTests::testMaxRequestSize - pytest.PytestUnraisableExceptionWarning: Exception ignored in:...`

Full test log is:

```
================================================================ test session starts ================================================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /root/b, configfile: pytest.ini
plugins: cov-2.10.1, services-2.2.1
collected 5 items                                                                                                                                   

cherrypy/test/test_config_server.py::ServerConfigTests::testAdditionalServers PASSED                                                          [ 20%]
cherrypy/test/test_config_server.py::ServerConfigTests::testBasicConfig PASSED                                                                [ 40%]
cherrypy/test/test_config_server.py::ServerConfigTests::testMaxRequestSize FAILED                                                             [ 60%]
cherrypy/test/test_config_server.py::ServerConfigTests::testMaxRequestSizePerHandler PASSED                                                   [ 80%]
cherrypy/test/test_config_server.py::ServerConfigTests::test_gc PASSED                                                                        [100%]

===================================================================== FAILURES ======================================================================
_______________________________________________________ ServerConfigTests.testMaxRequestSize ________________________________________________________

cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0xf5ff2bf8>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

cls        = <class '_pytest.runner.CallInfo'>
duration   = 0.1873577618971467
excinfo    = <ExceptionInfo PytestUnraisableExceptionWarning('Exception ignored in: <_io.FileIO [closed]>\n\nTraceback (most recent...2, in close\n    self.cpapp.release_serving()\nResourceWarning: unclosed file <_io.BufferedRandom name=19>\n') tblen=7>
func       = <function call_runtest_hook.<locals>.<lambda> at 0xf5ff2bf8>
precise_start = 5925879.650207272
precise_stop = 5925879.837565034
reraise    = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)
result     = None
start      = 1610724871.809948
stop       = 1610724871.9973373
when       = 'call'

/usr/lib/python3.8/site-packages/_pytest/runner.py:311: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>       lambda: ihook(item=item, **kwds), when=when, reraise=reraise
    )

ihook      = <_HookCaller 'pytest_runtest_call'>
item       = <TestCaseFunction testMaxRequestSize>
kwds       = {}

/usr/lib/python3.8/site-packages/_pytest/runner.py:255: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_HookCaller 'pytest_runtest_call'>, args = (), kwargs = {'item': <TestCaseFunction testMaxRequestSize>}, notincall = set()

    def __call__(self, *args, **kwargs):
        if args:
            raise TypeError("hook calling supports only keyword arguments")
        assert not self.is_historic()
        if self.spec and self.spec.argnames:
            notincall = (
                set(self.spec.argnames) - set(["__multicall__"]) - set(kwargs.keys())
            )
            if notincall:
                warnings.warn(
                    "Argument(s) {} which are declared in the hookspec "
                    "can not be found in this hook call".format(tuple(notincall)),
                    stacklevel=2,
                )
>       return self._hookexec(self, self.get_hookimpls(), kwargs)

args       = ()
kwargs     = {'item': <TestCaseFunction testMaxRequestSize>}
notincall  = set()
self       = <_HookCaller 'pytest_runtest_call'>

/usr/lib/python3.8/site-packages/pluggy/hooks.py:286: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.config.PytestPluginManager object at 0xf76eeec8>, hook = <_HookCaller 'pytest_runtest_call'>
methods = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/usr/lib/python3.8/site-packages/_pytest/runner...in=<module '_pytest.unraisableexception' from '/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py'>>, ...]
kwargs = {'item': <TestCaseFunction testMaxRequestSize>}

    def _hookexec(self, hook, methods, kwargs):
        # called from all hookcaller instances.
        # enable_tracing will set its own wrapping function at self._inner_hookexec
>       return self._inner_hookexec(hook, methods, kwargs)

hook       = <_HookCaller 'pytest_runtest_call'>
kwargs     = {'item': <TestCaseFunction testMaxRequestSize>}
methods    = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/usr/lib/python3.8/site-packages/_pytest/runner...in=<module '_pytest.unraisableexception' from '/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py'>>, ...]
self       = <_pytest.config.PytestPluginManager object at 0xf76eeec8>

/usr/lib/python3.8/site-packages/pluggy/manager.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

hook = <_HookCaller 'pytest_runtest_call'>
methods = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/usr/lib/python3.8/site-packages/_pytest/runner...in=<module '_pytest.unraisableexception' from '/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py'>>, ...]
kwargs = {'item': <TestCaseFunction testMaxRequestSize>}

>   self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
        methods,
        kwargs,
        firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
    )

hook       = <_HookCaller 'pytest_runtest_call'>
kwargs     = {'item': <TestCaseFunction testMaxRequestSize>}
methods    = [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/usr/lib/python3.8/site-packages/_pytest/runner...in=<module '_pytest.unraisableexception' from '/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py'>>, ...]

/usr/lib/python3.8/site-packages/pluggy/manager.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    @pytest.hookimpl(hookwrapper=True, tryfirst=True)
    def pytest_runtest_call() -> Generator[None, None, None]:
>       yield from unraisable_exception_runtest_hook()


/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:88: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
E               
E               Traceback (most recent call last):
E                 File "/root/b/cherrypy/_cpwsgi.py", line 282, in close
E                   self.cpapp.release_serving()
E               ResourceWarning: unclosed file <_io.BufferedRandom name=19>

cm         = <_pytest.unraisableexception.catch_unraisable_exception object at 0xf604ed48>
err_msg    = 'Exception ignored in'
msg        = 'Exception ignored in: <_io.FileIO [closed]>\n\nTraceback (most recent call last):\n  File "/root/b/cherrypy/_cpwsgi.py", line 282, in close\n    self.cpapp.release_serving()\nResourceWarning: unclosed file <_io.BufferedRandom name=19>\n'

/usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
----------------------------------------------------------------- Captured log call -----------------------------------------------------------------
INFO     cherrypy.access.4127338968:_cplogging.py:283 127.0.0.1 - - [15/Jan/2021:15:34:31] "GET / HTTP/1.1" 200 4 "" ""
INFO     cherrypy.access.4127338968:_cplogging.py:283 127.0.0.1 - - [15/Jan/2021:15:34:31] "POST /upload HTTP/1.1" 200 8 "" ""
```

Is this the file?
`E               ResourceWarning: unclosed file <_io.BufferedRandom name=19>`

**Comment by webknjaz** [comment]
> Is this the file?
> `E ResourceWarning: unclosed file <_io.BufferedRandom name=19>`

I think so but you'd need to stick a debugger there to learn where it originates.

FWIW I've made pytest ignore those warnings so if you want to fix more of those, you'll need to comment out the ignores in `pytest.ini`. But for now, they'll stop annoying un in the CI.

**Comment by webknjaz** [comment]
> pytest cherrypy/test/test_config_server.py --tb=long

This is what I use personally:
```console
$ pip install tox
$ tox --notest  # pre-populate the virtualenv, one-time
$ tox -- --no-cov -s cherrypy/test/test_config_server.py::ServerConfigTests::testMaxRequestSize
# you can also add -epy39 to run things under specific interpreter
```

**Comment by a16bitsysop** [comment]
Okay thanks, I added:
`-W ignore:unclosed:ResourceWarning`
To my pytest command and it ignores the rest of the unclosed sockets and files.
Might have a look sometime at others, it seems CherryPy is using python to close files and sockets which I thought was more pythonic but pytest6 checks program is closing them itself?

I made a patch for the timeout:

	
```diff
--- a/cherrypy/test/test_static.py
+++ b/cherrypy/test/test_static.py
@@ -76,7 +76,7 @@
         class Root:
 
             @cherrypy.expose
-            @cherrypy.config(**{'response.stream': True})
+            @cherrypy.config(**{'response.stream': True, 'server.socket_timeout': 5})
             def bigfile(self):
                 self.f = static.serve_file(bigfile_filepath)
                 return self.f
```

But it seems to mainly fail at first and succeed if restarted?

**Comment by webknjaz** [comment]
> Might have a look sometime at others, it seems CherryPy is using python to close files and sockets which I thought was more pythonic but pytest6 checks program is closing them itself?

There's nothing Pythonic about forgetting to close file handles :) Strictly speaking, it's a bug.

FWIW I tracked down that `<_io.BufferedRandom name=19>` and it turned out to be a file that is received by server via a POST request and passed into the handler method for `/upload` in the corresponding test server as a `file` argument: https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/test/test_config_server.py#L28. It's initialized as a `tempfile.TemporaryFile` @ https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/_cpreqbody.py#L513 and populated+assigned to the current request object @ https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/_cpreqbody.py#L245. Then, `LateParamPageHandler` extracts it into the handler kwargs @ https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/_cpdispatch.py#L232 and this is what gets passed into a handler @ https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/_cpdispatch.py#L54.
Although, I haven't found evidence of any code that cleans it up. So we **probably** have to make sure to close such file handles after https://github.com/cherrypy/cherrypy/blob/24dad62/cherrypy/_cprequest.py#L702.

> But it seems to mainly fail at first and succeed if restarted?

Not sure what you mean here.

**Comment by a16bitsysop** [comment]
Okay.

I mean in the alpine CI/CD gitlab it will fail the first build attempt for armv7 , put pass if the build is restarted!  Seems to affect cheroot actually, but same error message about timeout.

I think I have got it working now.

**Comment by webknjaz** [comment]
If you're saying that it's flaky in your CI, it probably is: depending on the load/concurrent jobs number on your arm worker nodes, some operations can become slower temporarily and that's what's causing you problems, as I see it.

**Comment by a16bitsysop** [comment]
Okay thanks
