### ISSUE TITLE
Totorial 09 "Data is all my live" python3.7 

### ISSUE THREAD

**Issue by cst-art** [cherrypy/cherrypy#1901]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
find no way with convert my database connection after upgrade py3.4 to py3.7

 tst with Touotial09 and become in Browser this message:

404 Not Found
The path '/generate' was not found.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cperror.py", line 416, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/generate' was not found.")
Powered by CherryPy 18.6.1.dev49+g98929b51

if i activate SSL ans scoped_session Error looks like:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 677, in _do_respond
    self.hooks.run('on_start_resource')
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 95, in run
    self.run_hooks(iter(sorted(self[point])))
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 117, in run_hooks
    hook()
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/_cprequest.py", line 65, in __call__
    return self.callback(**self.kwargs)
  File "/opt/secpi/tools/cp_sqlalchemy/tool.py", line 38, in bind_session
    cherrypy.engine.publish('db.bind', self.session)
  File "/usr/local/lib/python3.7/dist-packages/CherryPy-18.6.1.dev49+g98929b51-py3.7.egg/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: AttributeError("'DatabasePlugin' object has no attribute 'registry'")

**What is the current behavior?**
[24/Feb/2021:17:21:20] ENGINE Listening for SIGTERM.
[24/Feb/2021:17:21:20] ENGINE Listening for SIGHUP.
[24/Feb/2021:17:21:20] ENGINE Listening for SIGUSR1.
[24/Feb/2021:17:21:20] ENGINE Bus STARTING
[24/Feb/2021:17:21:20] ENGINE Started monitor thread 'Autoreloader'.
[24/Feb/2021:17:21:20] ENGINE Serving on http://127.0.0.1:8080
[24/Feb/2021:17:21:20] ENGINE Bus STARTED
127.0.0.1 - - [24/Feb/2021:17:21:48] "GET / HTTP/1.1" 200 345 "" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"
127.0.0.1 - - [24/Feb/2021:17:21:48] "GET /static/css/style.css HTTP/1.1" 404 1566 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"
127.0.0.1 - - [24/Feb/2021:17:22:04] "GET /generate?length=10 HTTP/1.1" 404 1542 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"
^C[24/Feb/2021:17:44:18] ENGINE Keyboard Interrupt: shutting down bus
[24/Feb/2021:17:44:18] ENGINE Bus STOPPING
[24/Feb/2021:17:44:18] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
[24/Feb/2021:17:44:18] ENGINE Stopped thread 'Autoreloader'.
[24/Feb/2021:17:44:18] ENGINE Bus STOPPED
[24/Feb/2021:17:44:18] ENGINE Bus EXITING
[24/Feb/2021:17:44:18] ENGINE Bus EXITED
[24/Feb/2021:17:44:18] ENGINE Waiting for child threads to terminate...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
Tutorial 09 tut09.py

**What is the expected behavior?**
update 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- Cheroot version: X.X.X
- CherryPy version: 18.6.1
- Python version: 3.7.X
- OS: raspi debian 10
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
- 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by webknjaz** [comment]
Could you post a reproducer? Without that, I doubt anyone would be able to understand what exactly you execute.

**Comment by webknjaz** [comment]
Looking at the tracebacks, it seems like your third-party tool `cp_sqlalchemy` is broken in one place and the handler for `/generate` missing. So fix those and it'll be fine, I guess. No way to know w/o the actual code.
