### ISSUE TITLE
Python3.11: "import cherrypy" gives AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

### ISSUE THREAD

**Issue by sanderjo** [cherrypy/cherrypy#1962]
**I'm submitting a ...**
- [X] bug report
- [X] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**

A bug, but against python 3.11, so maybe a feature request

**What is the current behavior?**
```
$ python3.11
Python 3.11.0b1 (main, May  9 2022, 23:45:52) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import cherrypy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/.local/lib/python3.11/site-packages/cherrypy/__init__.py", line 71, in <module>
    from . import _cpdispatch as dispatch
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sander/.local/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 209, in <module>
    getargspec = inspect.getargspec
                 ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
>>> 
```
and inspect:
```
$ python3.11
Python 3.11.0b1 (main, May  9 2022, 23:45:52) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect

>>> inspect.getarg
inspect.getargs(       inspect.getargvalues( 
```

... so no `inspect.getargspec`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

See above

**What is the expected behavior?**

Able to import (and use) cherrypy with python 3.11

**What is the motivation / use case for changing the behavior?**

Python 3.11 is now in beta, so time to prepare modules for it.
3.11.0 final: Monday, 2022-10-03

python 3.11 offers great speed improvements.

**Please tell us about your environment:**

- Cheroot version: 8.6.0
- CherryPy version: 18.6.1
- Python version: 3.11.0b1
- OS: Ubuntu 20.04 on x86_64
- Browser: all

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

**Comment by sanderjo** [comment]
Oh, seems the same as https://github.com/cherrypy/cherrypy/issues/1944

**Comment by sanderjo** [comment]
Proof it works with github version of cherrpy:

Fresh docker:
`docker run -it ubuntu:latest /bin/bash`

Setup:
```
apt update
apt install python3.11
apt install software-properties-common -y
add-apt-repository ppa:deadsnakes/ppa -y
apt update
apt install python3.11 python3.11-distutils python3-pip git-core   -y

git clone https://github.com/cherrypy/cherrypy.git
cd cherrypy/
python3.11 setup.py install
```

Proof:
```
root@4e2ab304ff63:~# python3.11 -c "import cherrypy; print(cherrypy.__version__)"
18.6.2.dev37+g5fff5e4b
```
No error anymore, and all well.
