### ISSUE TITLE
18.7.0: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [cherrypy/cherrypy#1972]
<!--
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Looks like sphinx (5.0.2) is failing on building documentation
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 56, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 56, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.7.0/docs/conf.py", line 56, in <module>
    prj_py_min_supported, prj_py_max_supported = map(
ValueError: not enough values to unpack (expected 2, got 0)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
Execute `sphinx-build -n -T -b man docs build/sphinx/man` in project root directory.

**What is the expected behavior?**
sphinx should generate documentation.

**What is the motivation / use case for changing the behavior?**
N/A
**Please tell us about your environment:**

- Cheroot version:  18.7.0
- CherryPy version: 8.6.0
- Python version: 3.8.13
- OS: Linux x86/.64
- Browser: N/A

**Other information**
List of modules installed in build env
```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
appdirs                       1.4.4
attrs                         22.1.0.dev0
Babel                         2.10.2
Brlapi                        0.8.3
build                         0.8.0
charset-normalizer            2.1.0
cheroot                       8.6.0
codespell                     2.1.0
colorama                      0.4.4
coverage                      6.4.2
cssselect                     1.1.0
cycler                        0.11.0
distro                        1.7.0
docopt                        0.6.2
docutils                      0.17.1
extended-project              1.2.3
extras                        1.0.0
fixtures                      4.0.0
fonttools                     4.34.4
gpg                           1.17.1-unknown
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.12.0
importlib-resources           5.8.0
iniconfig                     1.1.1
jaraco.classes                3.2.1
jaraco.collections            3.5.2
jaraco.context                4.1.2
jaraco.functools              3.5.1
jaraco.packaging              9.0.0
jaraco.text                   3.8.1
Jinja2                        3.1.1
kiwisolver                    1.4.4
libcomps                      0.1.18
louis                         3.22.0
lxml                          4.9.1
MarkupSafe                    2.1.1
matplotlib                    3.5.2
more-itertools                8.13.0
numpy                         1.23.1
olefile                       0.46
packaging                     21.3
path                          16.4.0
pbr                           5.8.1
pep517                        0.12.0
Pillow                        9.2.0
pip                           22.0.4
pluggy                        1.0.0
portend                       3.1.0
py                            1.11.0
Pygments                      2.12.0
PyGObject                     3.42.2
pyparsing                     3.0.9
pytest                        7.1.2
pytest-cov                    3.0.0
pytest-watch                  4.2.0
python-dateutil               2.8.2
pytz                          2022.1
requests                      2.28.1
requests-toolbelt             0.9.1
rpm                           4.17.0
rst.linker                    2.3.0
scour                         0.38.2
setuptools                    63.2.0
setuptools-scm                7.0.5
simple-project                1.2.3
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        5.0.2
sphinxcontrib-apidoc          0.3.0
sphinxcontrib-applehelp       1.0.2.dev20220714
sphinxcontrib-devhelp         1.0.2.dev20220714
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220712
sphinxcontrib-qthelp          1.0.3.dev20220712
sphinxcontrib-serializinghtml 1.1.5
tempora                       5.0.2
testtools                     2.5.0
tomli                         2.0.1
typing_extensions             4.2.0
urllib3                       1.26.9
watchdog                      2.1.9
wheel                         0.37.1
zc.lockfile                   2.0
zipp                          3.8.1
```

**Comment by kloczek** [comment]
Gosh just found that somehow this ticket has been oipened without proper details.

Here it is 
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v6.1.3

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.8.0/docs/conf.py", line 47, in <module>
    prj_meta = importlib.metadata.metadata('cherrypy')
AttributeError: module 'importlib' has no attribute 'metadata'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 279, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 364, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.8.0/docs/conf.py", line 47, in <module>
    prj_meta = importlib.metadata.metadata('cherrypy')
AttributeError: module 'importlib' has no attribute 'metadata'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 351, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/tkloczko/rpmbuild/BUILD/cherrypy-18.8.0/docs/conf.py", line 47, in <module>
    prj_meta = importlib.metadata.metadata('cherrypy')
AttributeError: module 'importlib' has no attribute 'metadata'
```
</details>

**Comment by webknjaz** [comment]
That import shouldn't fail under Python 3.8 since it's a part of stdlib. Your CPython install is probably incomplete or broken, nothing to do on our side.
