### ISSUE TITLE
ENGINE Error in HTTPServer.serve ssl.SSLError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)

### ISSUE THREAD

**Issue by Wissperwind** [cherrypy/cherrypy#1989]
Hi,

Today I visited a production server that stopped working. In the server log I noticed a bunch of tracebacks in ssl code:
```python-traceback

[22/Jan/2023:08:43:24] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1823, in serve
    self._connections.run(self.expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 203, in run
    self._run(expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 246, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 300, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\ssl\builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLError: [SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:997)

[22/Jan/2023:08:43:46] ENGINE socket.error 8
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 719, in parse_request
    success = self.read_request_line()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 778, in read_request_line
    self.simple_response(
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

Exception in thread ('CP Server Thread-16',):
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 719, in parse_request
    success = self.read_request_line()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 778, in read_request_line
    self.simple_response(
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\workers\threadpool.py", line 125, in run
    keep_conn_open = conn.communicate()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1319, in communicate
    self._conditional_error(req, '500 Internal Server Error')
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1362, in _conditional_error
    req.simple_response(response)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)
[22/Jan/2023:08:43:47] ENGINE socket.error 8
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 719, in parse_request
    success = self.read_request_line()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 778, in read_request_line
    self.simple_response(
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

Exception in thread ('CP Server Thread-14',):
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 719, in parse_request
    success = self.read_request_line()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 778, in read_request_line
    self.simple_response(
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\workers\threadpool.py", line 125, in run
    keep_conn_open = conn.communicate()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1319, in communicate
    self._conditional_error(req, '500 Internal Server Error')
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1362, in _conditional_error
    req.simple_response(response)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)
[22/Jan/2023:08:46:11] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1823, in serve
    self._connections.run(self.expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 203, in run
    self._run(expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 246, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 300, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\ssl\builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLError: [SSL] internal error (_ssl.c:997)

[22/Jan/2023:09:59:48] ENGINE Error in HTTPServer.serve
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1823, in serve
    self._connections.run(self.expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 203, in run
    self._run(expiration_interval)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 246, in _run
    new_conn = self._from_server_socket(self.server.socket)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\connections.py", line 300, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\ssl\builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLError: [SSL] internal error (_ssl.c:997)

[22/Jan/2023:09:59:59] ENGINE socket.error 8
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 987, in read_request_headers
    self.header_reader(self.rfile, self.inheaders)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 213, in __call__
    raise ValueError('Illegal end of headers.')
ValueError: Illegal end of headers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 732, in parse_request
    success = self.read_request_headers()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 989, in read_request_headers
    self.simple_response('400 Bad Request', ex.args[0])
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

Exception in thread ('CP Server Thread-8',):
Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 987, in read_request_headers
    self.header_reader(self.rfile, self.inheaders)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 213, in __call__
    raise ValueError('Illegal end of headers.')
ValueError: Illegal end of headers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1290, in communicate
    req.parse_request()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 732, in parse_request
    success = self.read_request_headers()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 989, in read_request_headers
    self.simple_response('400 Bad Request', ex.args[0])
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\workers\threadpool.py", line 125, in run
    keep_conn_open = conn.communicate()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1319, in communicate
    self._conditional_error(req, '500 Internal Server Error')
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1362, in _conditional_error
    req.simple_response(response)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\server.py", line 1128, in simple_response
    self.conn.wfile.write(EMPTY.join(buf))
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 438, in write
    res = super().write(val, *args, **kwargs)
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 36, in write
    self._flush_unlocked()
  File "D:\some\folder\python-windows\Lib\site-packages\cheroot\makefile.py", line 45, in _flush_unlocked
    n = self.raw.write(bytes(self._write_buf))
  File "socket.py", line 723, in write
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)
```

Is there anything known about this already?
I don't see an event that caused this exceptions. They seem to have happened from time to time until the server was not accessible anymore. This is from CP Server Thread-16 but other threads printed similar tracebacks.

**Comment by Wissperwind** [comment]
Is a vulnerability scanner able to crash cherrypy threads?
Might this Issue be related?
https://github.com/cherrypy/cheroot/pull/365

**Comment by mzhukovs** [comment]
Hi @webknjaz - any thoughts/updates on this one? I am running into the same issue and am considering just manually patching the code with the same update as in the PR that the OP linked to above #365 - would that do the trick?

Would really appreciate any insight , thank you

**Comment by webknjaz** [comment]
I wasn't able to look into this during the PyCon US Sprints. I wasn't satisfied with earlier solution proposals and need to dig deeper myself. Those may provide partial workarounds and you can try them out through monkeypatching. But to make them merge-worthy, more substantial changes would likely be needed.

**Comment by mzhukovs** [comment]
Thanks appreciate that update and makes perfect sense - cheers

**Comment by Wissperwind** [comment]
Hi
What is the current state?
The related issue has now been closed.

**Comment by webknjaz** [comment]
Cheroot 10.0.1 should now prevent the threads from dying.
