### ISSUE TITLE
When will there a new release?

### ISSUE THREAD

**Issue by Safihre** [cherrypy/cherrypy#1995]
When will there a new release?
Seems there have been plenty of updates since July last year?

Triggered by the constant  `DeprecationWarning`'s when running our tests due to cherrypy...

**Comment by webknjaz** [comment]
I suppose I could look into it.. Though, it seems like I'll first need to do some CI housekeeping that I haven't finished earlier...

**Comment by thezoggy** [comment]
just following back up on this to see if there was a roadmap of when next release will be, been awhile since the last

**Comment by Safihre** [comment]
Can you please just release a new version? It's been 1.5 **years**!
@jaraco maybe you can help?

**Comment by jaraco** [comment]
I tried cutting a manual release, but cherrypy is pinned to an old, broken version of Setuptools, so even cutting a release is not possible without additional engineering.

<details>

```
 cherrypy main @ pyproject-build .
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 45, < 60.9.0, setuptools_scm[toml] >= 3.5, setuptools_scm_git_archive >= 1.1)
* Getting build dependencies for sdist...
Traceback (most recent call last):
  File "/Users/jaraco/.local/pipx/venvs/build/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/Users/jaraco/.local/pipx/venvs/build/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/.local/pipx/venvs/build/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 281, in get_requires_for_build_sdist
    backend = _build_backend()
              ^^^^^^^^^^^^^^^^
  File "/Users/jaraco/.local/pipx/venvs/build/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.0_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/build-env-5926q3g0/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/build-env-5926q3g0/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/private/var/folders/sx/n5gkrgfx6zd91ymxr2sr9wvw00n8zm/T/build-env-5926q3g0/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2178, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_sdist
```

</details>

**Comment by jaraco** [comment]
I've tagged 18.9.0 and released it to PyPI.

@webknjaz Please let me know when you plan to fix the issues with CI or if you'd prefer me to take over maintenance.

**Comment by webknjaz** [comment]
@jaraco hi, I do plan to fix it. Thanks for stepping in!

**Comment by Safihre** [comment]
Oh, I assumed this would fix the `DeprecationWarning` about `cgi` removal in 3.13.. But it does not.

But glad a release is out anyway :)

**Comment by thezoggy** [comment]
looks like the two outstanding issues are:

pkg_resources - https://github.com/cherrypy/cherrypy/issues/2019
CGI - https://github.com/cherrypy/cherrypy/issues/2020

hopefully warrant a new build after these are solved

**Comment by jaraco** [comment]
v18.10.0 addresses #2020.
