### ISSUE TITLE
[Discussion/Bug] Replace `jaraco.collections.KeyTransformingDict` to avoid breaks in Bazel builds

### ISSUE THREAD

**Issue by rahul-theorem** [cherrypy/cherrypy#2002]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
Bug/discussion

**What is the current behavior?**
We're using `rules_python` to manage our Python dependencies/toolchain in our Bazel build, and a library we're using (`scoutsuite`) that depends on `cherrypy` is leading to an error while resolving dependencies (stacktrace at bottom). This is due to a number of long-standing issues where `jaraco.text` has a space in a file (`Lorem ipsum.txt`) it loads on import, and Bazel doesn't support spaces in file names due to a number of reasons about its internal runfiles manifest structure (see https://github.com/bazelbuild/bazel/issues/4327)

This is pulled into `cherrypy` by `jaraco.collections.KeyTransformingDict` in `httputils.py`. To support using `cherrypy` in a bazel build w/ `rules_python`/`pip_compile`, it'd be fairly straightforward to replace the `KeyTransformingDict` import from `jaraco.collections` with a version that's vendored in the repo

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**
Add `cherrypy` as a dependency in a Bazel build using `rules_python` and attempt to build any target that depends on it

**Please tell us about your environment:**

- Cheroot version: 10.0.0
- CherryPy version: 18.8.0
- Python version: 3.10.8
- OS: MacOS 13.6
- Browser: N/A

**Other information** 

Stacktrace when attempting to resolve requirements:

<details>

```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/_main/rules_python_entry_point_scout.py", line 11, in <module>
    from ScoutSuite.__main__ import run_from_cli
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_scoutsuite/site-packages/ScoutSuite/__main__.py", line 15, in <module>
    from ScoutSuite.core.server import Server
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_scoutsuite/site-packages/ScoutSuite/core/server.py", line 2, in <module>
    import cherrypy
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_cherrypy/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_cherrypy/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_cherrypy/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_jaraco_collections/site-packages/jaraco/collections.py", line 12, in <module>
    import jaraco.text
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_jaraco_text/site-packages/jaraco/text/__init__.py", line 231, in <module>
    files(__name__).joinpath('Lorem ipsum.txt').read_text(encoding='utf-8')
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/external/rules_python~0.26.0~python~python_3_11_x86_64-apple-darwin/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/external/rules_python~0.26.0~python~python_3_11_x86_64-apple-darwin/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/tmp/_bazel/46aa123924747c319eb8f588f2d86f2a/execroot/_main/bazel-out/darwin-fastbuild/bin/scout.runfiles/rules_python~0.26.0~pip~deps_311_jaraco_text/site-packages/jaraco/text/Lorem ipsum.txt'
```

</details>

**Comment by jaraco** [comment]
Spaces are valid filenames in python packages and all modern file systems. The bug lies in Bazel.

Vendoring subsets of packages is not a solution, as it adds additional maintenance burden and toil to a project that's already laden with debt, and also implies that every other project must do the same.

The solution needs to be to fix the limitation in Bazel or write a routine to work around the issue at the integration layer (i.e. re-write jaraco.collections to not have the space), which is what Google does. For example, you might re-package `jaraco.text` without the `Lorem ipsum.txt` renamed and then install that.
