### ISSUE TITLE
Favicon Issue: staticfile() got multiple values for argument 'filename'

### ISSUE THREAD

**Issue by jbirch99** [cherrypy/cherrypy#2042]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

**Do you want to request a *feature* or report a *bug*?**
Report a bug 

**What is the current behavior?**
Cherrypy does not show my custom favicon.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

My code is, 

```python
import cherrypy

class HelloWorld:
   @cherrypy.expose
   def index(self):
       return "Hello World!"

if __name__ == '__main__':
    config = {
        '/favicon.ico':
        {
            'tools.staticfile.on': True,
            'tools.staticfile.filename': '/favicon.ico'
        }
    }
    cherrypy.config.update({"server.socket_port": 8181})
    cherrypy.config.update({"server.socket_host": "0.0.0.0"})
    cherrypy.quickstart(HelloWorld(), "/", config)
```

Logs: 

```bash
127.0.0.1 - - [03/Dec/2024:13:06:24] "GET / HTTP/1.1" 200 12 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
[03/Dec/2024:13:06:27] HTTP 
Traceback (most recent call last):
  File "/home/jbirch/dev/cherrypy/cherrypy_venv/lib/python3.12/site-packages/cherrypy/_cprequest.py", line 659, in respond
    self._do_respond(path_info)
  File "/home/jbirch/dev/cherrypy/cherrypy_venv/lib/python3.12/site-packages/cherrypy/_cprequest.py", line 718, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/home/jbirch/dev/cherrypy/cherrypy_venv/lib/python3.12/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbirch/dev/cherrypy/cherrypy_venv/lib/python3.12/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jbirch/dev/cherrypy/cherrypy_venv/lib/python3.12/site-packages/cherrypy/_cptools.py", line 175, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: staticfile() got multiple values for argument 'filename'
[03/Dec/2024:13:06:27] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:8181
  CONNECTION: keep-alive
  AUTHORIZATION: Basic YWRtaW46
  SEC-CH-UA-PLATFORM: "Windows"
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
  SEC-CH-UA: "Microsoft Edge";v="131", "Chromium";v="131", "Not_A Brand";v="24"
  SEC-CH-UA-MOBILE: ?0
  ACCEPT: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
  SEC-FETCH-SITE: same-origin
  SEC-FETCH-MODE: no-cors
  SEC-FETCH-DEST: image
  REFERER: http://localhost:8181/
  ACCEPT-ENCODING: gzip, deflate, br, zstd
  ACCEPT-LANGUAGE: en-US,en;q=0.9,en-GB;q=0.8
  COOKIE: experimentsId=1715362555; intercom-id-nptsh54m=532e4a5b-4014-472b-b31e-a4169e147771; intercom-device-id-nptsh54m=1c30db66-2109-4469-a656-d98a628382b4
127.0.0.1 - - [03/Dec/2024:13:06:27] "GET /favicon.ico HTTP/1.1" 500 1985 "http://localhost:8181/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
```

To reproduce, 

1. Put the code in a file called `root.py`.
2. Create an ico file containing an image and name it favicon.ico in the same directory as `root.py`.
3. Run the server `python3 root.py`
4. Go to [http://localhost:8181/](http://localhost:8181/)

The default cherrypy icon shows instead of the custom one and there is an error message in the logs.,

![image](https://github.com/user-attachments/assets/d1bde4f9-8b0a-4a4f-905b-9ab2bee98ec7)

**What is the expected behavior?**
The custom icon should show when I load the page and there should be no error message in the logs.

**What is the motivation / use case for changing the behavior?**
Have the custom icon load and no error message in the logs.

**Please tell us about your environment:**

- Cheroot version: 10.0.1
- CherryPy version: 18.10.0
- Python version: 3.12.7
- OS: Windows 11 WSL v2 -> Ubuntu 22.04.4 LTS
- Browser: [Microsoft Edge 131.0.2903.70]

Thanks :)

**Comment by kmcdebs** [comment]
@jbirch99, is the path to you favicon image absolute, or relative? I think [CherryPy wants the absolute path](https://docs.cherrypy.dev/en/latest/basics.html#serving-a-whole-directory). You might just need to use the full path to your favicon file.

Also, beware of the favicon cache. I had to clear my browser history in order to get the updated favicon here.

 Let me know if this works for you. 
``` python
import cherrypy

class HelloWorld:
   @cherrypy.expose
   def index(self):
       return "Hello World!"

if __name__ == '__main__':
    config = {
        '/favicon.ico':
        {
            'tools.staticfile.on': True,
            'tools.staticfile.filename': ‘/an/absolute/filepath/to/favicon.ico'
        }
    }
    cherrypy.config.update({"server.socket_port": 8181})
    cherrypy.config.update({"server.socket_host": "0.0.0.0"})
    cherrypy.quickstart(HelloWorld(), "/", config)
```

**Comment by jbirch99** [comment]
yes this does fix the issue. I just had to use ` os.path.join(os.path.dirname(__file__), "favicon.ico")`. 

Thanks for the help :)
