### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#589]
Originally reported by: **Robert Brewer (Bitbucket: [fumanchu](http://bitbucket.org/fumanchu), GitHub: [fumanchu](http://github.com/fumanchu))**

----------------------------------------

    
    C:\Python24\Lib\site-packages>python cherrypy\test\test.py --ssl
    Python version used to run this test script: 2.4.2
    CherryPy version 3.0.0beta2
    HTTP server version HTTP/1.1 (ssl)
    
    ...
    
    test_1_Ram_Concurrency (test_session.SessionTest) ... Exception in thread CP WSGIServer Thread-4:
    Traceback (most recent call last):
      File "C:\Python24\Lib\threading.py", line 442, in __bootstrap
        self.run()
      File "C:\Python24\Lib\site-packages\cherrypy\_cpwsgiserver.py", line 506, in run
        conn.communicate()
      File "C:\Python24\Lib\site-packages\cherrypy\_cpwsgiserver.py", line 471, in communicate
        req.simple_response("500 Internal Server Error", format_exc())
      File "C:\Python24\Lib\site-packages\cherrypy\_cpwsgiserver.py", line 296, in simple_response
        wfile.flush()
      File "C:\Python24\Lib\site-packages\cherrypy\_cpwsgiserver.py", line 365, in ssl_method_wrapper
        return method(self, *args, **kwargs)
      File "C:\Python24\Lib\socket.py", line 243, in flush
        self._sock.sendall(buffer)
    Error: [('SSL routines', 'SSL3_GET_MESSAGE', 'excessive message size')]
    

----------------------------------------
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/589

**Comment by jaraco** [comment]
I'm going to assume this was fixed or is no longer relevant.
