### ISSUE TITLE
A value of 0 for socket_port should cause CP to bind to an available unused port

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#645]
Originally reported by: **Anonymous**

---

When socket_port is specified as 0, an exception is thrown as follows:

```
File
"/localhome/raghu/localwork/cherrypy/svn.cherrypy.org/trunk/cherrypy/_cpserver.py",
line 69, in quickstart
    self.start()
  File
"/localhome/raghu/localwork/cherrypy/svn.cherrypy.org/trunk/cherrypy/_cpserver.py",
line 95, in start
    self._start_http(httpserver)
  File
"/localhome/raghu/localwork/cherrypy/svn.cherrypy.org/trunk/cherrypy/_cpserver.py",
line 118, in _start_http
    self.wait(httpserver)
  File
"/localhome/raghu/localwork/cherrypy/svn.cherrypy.org/trunk/cherrypy/_cpserver.py",
line 159, in wait
    wait_for_occupied_port(*bind_addr)
  File
"/localhome/raghu/localwork/cherrypy/svn.cherrypy.org/trunk/cherrypy/_cpserver.py",
line 247, in wait_for_occupied_port
    raise IOError(msg)
IOError: Port 0 not bound on 'localhost'
```

I am using the latest code from the trunk. It appears to me that even though wsgiserver is properly passing 0 to socket.bind (and hence binding to an unused port), other parts of the code still use "configured" port which is 0. 

Reported by draghuram@gmail.com

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/645

**Comment by jaraco** [comment]
I confirmed this issue still exists. Running this code:

```
import cherrypy

class Server:
	@classmethod
	def run(cls):
		config = {
			'global': {
				'server.socket_port': 0,
			}
		}
		cherrypy.quickstart(cls(), config=config)

if __name__ == '__main__':
	Server.run()
```

produces this output

```
[01/May/2016:15:31:00] ENGINE Listening for SIGHUP.
[01/May/2016:15:31:00] ENGINE Listening for SIGTERM.
[01/May/2016:15:31:00] ENGINE Listening for SIGUSR1.
[01/May/2016:15:31:00] ENGINE Bus STARTING
[01/May/2016:15:31:01] ENGINE Started monitor thread '_TimeoutMonitor'.
[01/May/2016:15:31:01] ENGINE Started monitor thread 'Autoreloader'.
[01/May/2016:15:31:51] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x101fd0828>>
Traceback (most recent call last):
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/wspbus.py", line 203, in publish
    output.append(listener(*args, **kwargs))
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/servers.py", line 177, in start
    self.wait()
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/servers.py", line 232, in wait
    wait_for_occupied_port(host, port)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/servers.py", line 458, in wait_for_occupied_port
    raise IOError("Port %r not bound on %r" % (port, host))
OSError: Port 0 not bound on '127.0.0.1'

[01/May/2016:15:31:51] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/wspbus.py", line 241, in start
    self.publish('start')
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/process/wspbus.py", line 221, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("Port 0 not bound on '127.0.0.1'",)

[01/May/2016:15:31:51] ENGINE Bus STOPPING
[01/May/2016:15:31:51] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 0)) already shut down
[01/May/2016:15:31:51] ENGINE Stopped thread 'Autoreloader'.
[01/May/2016:15:31:51] ENGINE Stopped thread '_TimeoutMonitor'.
[01/May/2016:15:31:51] ENGINE Bus STOPPED
[01/May/2016:15:31:51] ENGINE Bus EXITING
[01/May/2016:15:31:51] ENGINE Bus EXITED
```

Note the 50 second timeout.

**Comment by webknjaz** [comment]
I think, I'll take a look at this issue.

**Comment by jaraco** [comment]
I hadn't meant to push that commit to master. I've moved it to the feature/bind-ephemeral branch.
