### ISSUE TITLE
CP_BufferedWriter broken for python 3

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#920]
Originally reported by: **jroesslein (Bitbucket: [jroesslein](http://bitbucket.org/jroesslein), GitHub: Unknown)**

---

Python 3 now uses a C module for IO. This means a lot of the attributes 
used by CP_BufferedWriter are no longer available (ex. _write_lock). 

Do we need a custom version of BufferedWriter?

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/920

**Comment by flberger** [comment]
With CherryPy 18.1.0 on Python 3.6.8 on Cygwin MS Win10, I get

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1252, in communicate
        req.respond()
      File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1056, in respond
        self.server.gateway(self).respond()
      File "/usr/lib/python3.6/site-packages/cheroot/wsgi.py", line 147, in respond
        self.write(chunk)
      File "/usr/lib/python3.6/site-packages/cheroot/wsgi.py", line 226, in write
        self.req.ensure_headers_sent()
      File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1103, in ensure_headers_sent
        self.send_headers()
      File "/usr/lib/python3.6/site-packages/cheroot/server.py", line 1188, in send_headers
        self.conn.wfile.write(EMPTY.join(buf))
      File "/usr/lib/python3.6/site-packages/cheroot/makefile.py", line 34, in write
        with self._write_lock:
    AttributeError: 'StreamWriter' object has no attribute '_write_lock'

for a simple test application.

Apparently the missing attribute _write_lock is a problem now.

How can I fix this?

**Comment by webknjaz** [comment]
@flberger oh wow!
We never tested such env combo. Anyway, you might want to file a proper issue against Cheroot project where the exception of your traceback originates. Please make sure to fill out as many details as possible and be ready to help with troubleshooting as we don't have such setup on our machines.

**Comment by flberger** [comment]
Thank you, I'll post it there.
